In [2]:
import duckdb

In [4]:
con = duckdb.connect('../data/practice.duckdb')

In [5]:
con.sql("CREATE TABLE calendar AS SELECT * FROM '../data/raw/calendar.csv'")

In [7]:
con.sql("SHOW TABLES").df()

       name
0  calendar

In [2]:
import duckdb

In [3]:
con = duckdb.connect('../data/practice.duckdb')

In [4]:
con.sql('SHOW TABLES').df()

       name
0  calendar

In [5]:
con.sql("DESCRIBE calendar").df()

     column_name column_type null   key default extra
0           date        DATE  YES  None    None  None
1       wm_yr_wk      BIGINT  YES  None    None  None
2        weekday     VARCHAR  YES  None    None  None
3           wday      BIGINT  YES  None    None  None
4          month      BIGINT  YES  None    None  None
5           year      BIGINT  YES  None    None  None
6              d     VARCHAR  YES  None    None  None
7   event_name_1     VARCHAR  YES  None    None  None
8   event_type_1     VARCHAR  YES  None    None  None
9   event_name_2     VARCHAR  YES  None    None  None
10  event_type_2     VARCHAR  YES  None    None  None
11       snap_CA      BIGINT  YES  None    None  None
12       snap_TX      BIGINT  YES  None    None  None
13       snap_WI      BIGINT  YES  None    None  None

In [6]:
con.sql("DESCRIBE calendar")

┌──────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name  │ column_type │  null   │   key   │ default │  extra  │
│   varchar    │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ date         │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ wm_yr_wk     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ weekday      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ wday         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ month        │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ year         │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ d            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ event_name_1 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ event_type_1 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ event_name_2 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ event_type_2 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ snap_CA      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ snap_TX      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ snap_WI      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  14 rows                                                  6 columns

In [9]:
con.sql("SELECT * FROM calendar LIMIT 5").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,None,None,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,None,None,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,None,None,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,None,None,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,None,None,None,None,1,0,1

In [10]:
con.sql("SELECT date, weekday FROM calendar LIMIT 5").df()

        date    weekday
0 2011-01-29   Saturday
1 2011-01-30     Sunday
2 2011-01-31     Monday
3 2011-02-01    Tuesday
4 2011-02-02  Wednesday

In [12]:
con.sql("SELECT date,weekday FROM calendar").df()

           date    weekday
0    2011-01-29   Saturday
1    2011-01-30     Sunday
2    2011-01-31     Monday
3    2011-02-01    Tuesday
4    2011-02-02  Wednesday
...         ...        ...
1964 2016-06-15  Wednesday
1965 2016-06-16   Thursday
1966 2016-06-17     Friday
1967 2016-06-18   Saturday
1968 2016-06-19     Sunday

[1969 rows x 2 columns]

In [14]:
con.sql("SELECT date, weekday, wm_yr_wk FROM calendar LIMIT 5").df()

        date    weekday  wm_yr_wk
0 2011-01-29   Saturday     11101
1 2011-01-30     Sunday     11101
2 2011-01-31     Monday     11101
3 2011-02-01    Tuesday     11101
4 2011-02-02  Wednesday     11101

In [16]:
con.sql("SELECT date, weekday, wm_yr_wk FROM calendar WHERE weekday = 'Saturday' LIMIT 5").df()

        date   weekday  wm_yr_wk
0 2011-01-29  Saturday     11101
1 2011-02-05  Saturday     11102
2 2011-02-12  Saturday     11103
3 2011-02-19  Saturday     11104
4 2011-02-26  Saturday     11105

In [17]:
con.sql("SELECT date, weekday, year FROM calendar WHERE year <= '2012' LIMIT 5").df()

        date    weekday  year
0 2011-01-29   Saturday  2011
1 2011-01-30     Sunday  2011
2 2011-01-31     Monday  2011
3 2011-02-01    Tuesday  2011
4 2011-02-02  Wednesday  2011

In [20]:
con.sql("SELECT date, weekday, year FROM calendar WHERE weekday = 'Saturday' AND year = 2016 LIMIT 5").df()

        date   weekday  year
0 2016-01-02  Saturday  2016
1 2016-01-09  Saturday  2016
2 2016-01-16  Saturday  2016
3 2016-01-23  Saturday  2016
4 2016-01-30  Saturday  2016

In [22]:
con.sql("SELECT date, weekday FROM calendar WHERE weekday = 'Saturday' OR weekday = 'Sunday' LIMIT 10").df()

        date   weekday
0 2011-01-29  Saturday
1 2011-01-30    Sunday
2 2011-02-05  Saturday
3 2011-02-06    Sunday
4 2011-02-12  Saturday
5 2011-02-13    Sunday
6 2011-02-19  Saturday
7 2011-02-20    Sunday
8 2011-02-26  Saturday
9 2011-02-27    Sunday

In [24]:
c

        date  month  year
0 2011-11-01     11  2011
1 2011-11-02     11  2011
2 2011-11-03     11  2011
3 2011-11-04     11  2011
4 2011-11-05     11  2011
5 2011-11-06     11  2011
6 2011-11-07     11  2011
7 2011-11-08     11  2011
8 2011-11-09     11  2011
9 2011-11-10     11  2011

In [26]:
con.sql("SELECT date, weekday FROM calendar WHERE date BETWEEN '2015-12-20' AND '2015-12-31'").df()

         date    weekday
0  2015-12-20     Sunday
1  2015-12-21     Monday
2  2015-12-22    Tuesday
3  2015-12-23  Wednesday
4  2015-12-24   Thursday
5  2015-12-25     Friday
6  2015-12-26   Saturday
7  2015-12-27     Sunday
8  2015-12-28     Monday
9  2015-12-29    Tuesday
10 2015-12-30  Wednesday
11 2015-12-31   Thursday

In [27]:
con.sql("SELECT date, event_name_1 FROM calendar WHERE event_name_1 IS NOT NULL LIMIT 10").df()

        date    event_name_1
0 2011-02-06       SuperBowl
1 2011-02-14   ValentinesDay
2 2011-02-21   PresidentsDay
3 2011-03-09       LentStart
4 2011-03-16       LentWeek2
5 2011-03-17   StPatricksDay
6 2011-03-20       Purim End
7 2011-04-24  OrthodoxEaster
8 2011-04-26      Pesach End
9 2011-05-05   Cinco De Mayo

In [29]:
con.sql("SELECT date, event_name_1 FROM calendar WHERE event_name_1 LIKE '%Day'").df()

         date         event_name_1
0  2011-02-14        ValentinesDay
1  2011-02-21        PresidentsDay
2  2011-03-17        StPatricksDay
3  2011-05-30          MemorialDay
4  2011-07-04      IndependenceDay
5  2011-09-05             LaborDay
6  2011-10-10          ColumbusDay
7  2011-11-11          VeteransDay
8  2012-01-16  MartinLutherKingDay
9  2012-02-14        ValentinesDay
10 2012-02-20        PresidentsDay
11 2012-03-17        StPatricksDay
12 2012-05-28          MemorialDay
13 2012-07-04      IndependenceDay
14 2012-09-03             LaborDay
15 2012-10-08          ColumbusDay
16 2012-11-11          VeteransDay
17 2013-01-21  MartinLutherKingDay
18 2013-02-14        ValentinesDay
19 2013-02-18        PresidentsDay
20 2013-03-17        StPatricksDay
21 2013-05-27          MemorialDay
22 2013-07-04      IndependenceDay
23 2013-09-02             LaborDay
24 2013-10-14          ColumbusDay
25 2013-11-11          VeteransDay
26 2014-01-20  MartinLutherKingDay
27 2014-02-14        ValentinesDay
28 2014-02-17        PresidentsDay
29 2014-03-17        StPatricksDay
30 2014-05-26          MemorialDay
31 2014-07-04      IndependenceDay
32 2014-09-01             LaborDay
33 2014-10-13          ColumbusDay
34 2014-11-11          VeteransDay
35 2015-01-19  MartinLutherKingDay
36 2015-02-14        ValentinesDay
37 2015-02-16        PresidentsDay
38 2015-03-17        StPatricksDay
39 2015-05-25          MemorialDay
40 2015-07-04      IndependenceDay
41 2015-09-07             LaborDay
42 2015-10-12          ColumbusDay
43 2015-11-11          VeteransDay
44 2016-01-18  MartinLutherKingDay
45 2016-02-14        ValentinesDay
46 2016-02-15        PresidentsDay
47 2016-03-17        StPatricksDay
48 2016-05-30          MemorialDay

In [30]:
con.sql("SELECT date, event_name_1 FROM calendar WHERE event_name_1 LIKE '%Father%'").df()

        date  event_name_1
0 2011-06-19  Father's day
1 2012-06-17  Father's day
2 2013-06-16  Father's day
3 2015-06-21  Father's day

In [31]:
con.sql ("SELECT date, event_name_1 FROM calendar WHERE event_name_1 IS NOT NULL ORDER BY date DESC LIMIT 10").df()

        date    event_name_1
0 2016-06-19    NBAFinalsEnd
1 2016-06-07  Ramadan starts
2 2016-06-02  NBAFinalsStart
3 2016-05-30     MemorialDay
4 2016-05-08    Mother's day
5 2016-05-05   Cinco De Mayo
6 2016-05-01  OrthodoxEaster
7 2016-04-30      Pesach End
8 2016-03-27          Easter
9 2016-03-24       Purim End

In [34]:
con.sql("SELECT DISTINCT weekday FROM calendar ORDER BY wday").df()

     weekday
0   Saturday
1     Sunday
2     Monday
3    Tuesday
4  Wednesday
5   Thursday
6     Friday

In [36]:
con.sql("SELECT DISTINCT event_type_1 FROM calendar WHERE event_type_1 IS NOT NULL ORDER BY event_type_1").df()

  event_type_1
0     Cultural
1     National
2    Religious
3     Sporting

In [39]:
con.sql("SELECT COUNT(*) FROM calendar").df()

   count_star()
0          1969

In [41]:
con.sql("SELECT COUNT (event_type_1) FROM calendar").df()

   count(event_type_1)
0                  162

In [42]:
con.sql("SELECT COUNT (event_type_1) FROM calendar WHERE weekday = 'Saturday'").df()

   count(event_type_1)
0                   11

In [44]:
con.sql("SELECT COUNT(*) FROM calendar WHERE weekday = 'Saturday'").df()

   count_star()
0           282

In [45]:
con.sql("SELECT MIN(date), MAX(date) FROM calendar").df()

   min(date)  max(date)
0 2011-01-29 2016-06-19

In [47]:
con.sql("SELECT date, snap_CA FROM calendar LIMIT 10").df()

        date  snap_CA
0 2011-01-29        0
1 2011-01-30        0
2 2011-01-31        0
3 2011-02-01        1
4 2011-02-02        1
5 2011-02-03        1
6 2011-02-04        1
7 2011-02-05        1
8 2011-02-06        1
9 2011-02-07        1

In [49]:
con.sql("SELECT MAX(date), MIN(date), SUM(snap_CA) FROM calendar").df()

   max(date)  min(date)  sum(snap_CA)
0 2016-06-19 2011-01-29         650.0

In [50]:
con.sql("SELECT MAX(date) AS last_day, MIN(date) AS first_day, SUM(snap_CA) AS snap_days_ca FROM calendar").df()

    last_day  first_day  snap_days_ca
0 2016-06-19 2011-01-29         650.0

In [51]:
con.sql("SELECT COUNT(*) AS days FROM calendar GROUP BY year").df()

   days
0   337
1   366
2   365
3   365
4   365
5   171

In [55]:
con.sql("SELECT year, SUM(snap_CA) AS snap_days FROM calendar GROUP BY year ORDER BY year").df()

   year  snap_days
0  2011      110.0
1  2012      120.0
2  2013      120.0
3  2014      120.0
4  2015      120.0
5  2016       60.0

In [57]:
con.sql("SELECT year, SUM(snap_CA) AS snap_days FROM calendar Group by year Having SUM(snap_CA)<120").df()

   year  snap_days
0  2011      110.0
1  2016       60.0

In [59]:
con.sql("SELECT * FROM calendar LIMIT 10").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,None,None,1,0,1
5,2011-02-03,11101,Thursday,6,2,2011,d_6,NaN,NaN,None,None,1,1,1
6,2011-02-04,11101,Friday,7,2,2011,d_7,NaN,NaN,None,None,1,0,0
7,2011-02-05,11102,Saturday,1,2,2011,d_8,NaN,NaN,None,None,1,1,1
8,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,None,None,1,1,1
9,2011-02-07,11102,Monday,3,2,2011,d_10,NaN,NaN,None,None,1,1,0

In [62]:
con.sql("SELECT event_type_1,COUNT(event_type_1) AS event_days FROM calendar WHERE event_type_1 IS NOT NULL GROUP BY event_type_1 Having COUNT(event_type_1)>30").df()

  event_type_1  event_days
0    Religious          55
1     Cultural          37
2     National          52

In [64]:
con.sql("SELECT date, CASE WHEN weekday IN ('Saturday', 'Sunday') THEN 'Weekend' ELSE 'Weekday' END AS day_type FROM calendar LIMIT 10").df()

        date day_type
0 2011-01-29  Weekend
1 2011-01-30  Weekend
2 2011-01-31  Weekday
3 2011-02-01  Weekday
4 2011-02-02  Weekday
5 2011-02-03  Weekday
6 2011-02-04  Weekday
7 2011-02-05  Weekend
8 2011-02-06  Weekend
9 2011-02-07  Weekday

In [67]:
con.sql("SELECT date, event_name_1, CASE WHEN event_name_1 IS NULL THEN 'NO' ELSE 'YES' END AS has_event FROM calendar LIMIT 10").df()

        date event_name_1 has_event
0 2011-01-29          NaN        NO
1 2011-01-30          NaN        NO
2 2011-01-31          NaN        NO
3 2011-02-01          NaN        NO
4 2011-02-02          NaN        NO
5 2011-02-03          NaN        NO
6 2011-02-04          NaN        NO
7 2011-02-05          NaN        NO
8 2011-02-06    SuperBowl       YES
9 2011-02-07          NaN        NO

In [70]:
con.sql("SELECT year, COUNT (event_name_1) AS event_days FROM calendar WHERE event_name_1 IS NOT NULL GROUP BY year ORDER BY year").df()

   year  event_days
0  2011          26
1  2012          30
2  2013          29
3  2014          28
4  2015          30
5  2016          19

In [72]:
con.sql("SELECT * FROM calendar LIMIT 10").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,None,None,1,0,1
5,2011-02-03,11101,Thursday,6,2,2011,d_6,NaN,NaN,None,None,1,1,1
6,2011-02-04,11101,Friday,7,2,2011,d_7,NaN,NaN,None,None,1,0,0
7,2011-02-05,11102,Saturday,1,2,2011,d_8,NaN,NaN,None,None,1,1,1
8,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,None,None,1,1,1
9,2011-02-07,11102,Monday,3,2,2011,d_10,NaN,NaN,None,None,1,1,0

In [77]:
con.sql("SELECT month, SUM(snap_TX) AS snap_days_tx FROM calendar GROUP BY month HAVING SUM(snap_TX)>50 ORDER BY SUM(snap_TX) DESC").df()

   month  snap_days_tx
0      2          60.0
1      3          60.0
2      4          60.0
3      5          60.0
4      6          60.0

In [82]:
con.sql("SELECT date, weekday, event_name_1, CASE WHEN month IN(12,1,2) THEN 'Winter' WHEN month IN(6,7,8) THEN 'Summer' ELSE 'Other' END AS season FROM calendar WHERE event_name_1 IS NOT NULL ORDER BY date LIMIT 15").df()

         date    weekday    event_name_1  season
0  2011-02-06     Sunday       SuperBowl  Winter
1  2011-02-14     Monday   ValentinesDay  Winter
2  2011-02-21     Monday   PresidentsDay  Winter
3  2011-03-09  Wednesday       LentStart   Other
4  2011-03-16  Wednesday       LentWeek2   Other
5  2011-03-17   Thursday   StPatricksDay   Other
6  2011-03-20     Sunday       Purim End   Other
7  2011-04-24     Sunday  OrthodoxEaster   Other
8  2011-04-26    Tuesday      Pesach End   Other
9  2011-05-05   Thursday   Cinco De Mayo   Other
10 2011-05-08     Sunday    Mother's day   Other
11 2011-05-30     Monday     MemorialDay   Other
12 2011-05-31    Tuesday  NBAFinalsStart   Other
13 2011-06-12     Sunday    NBAFinalsEnd  Summer
14 2011-06-19     Sunday    Father's day  Summer

In [84]:
con.sql("SELECT weekday, COUNT(weekday) AS total_days, COUNT(event_name_1) AS event_days FROM calendar GROUP BY weekday ORDER BY event_days DESC").df()

     weekday  total_days  event_days
0     Sunday         282          40
1     Monday         281          37
2   Thursday         281          28
3  Wednesday         281          21
4    Tuesday         281          17
5   Saturday         282          11
6     Friday         281           8

In [87]:
con.sql("SELECT year, MIN(date) AS first_date, MAX(date) AS last_date, SUM(snap_WI) AS snap_days_WI FROM calendar GROUP BY year HAVING (snap_days_WI)< 120 ORDER BY year").df()

   year first_date  last_date  snap_days_WI
0  2011 2011-01-29 2011-12-31         110.0
1  2016 2016-01-01 2016-06-19          60.0

In [91]:
con.sql("SELECT DISTINCT event_name_1, COUNT(event_name_1) AS event_times FROM calendar WHERE event_name_1 ILIKE '%Day%' GROUP BY event_name_1 ORDER BY event_name_1").df()

           event_name_1  event_times
0           ColumbusDay            5
1          Father's day            4
2       IndependenceDay            5
3              LaborDay            5
4   MartinLutherKingDay            5
5           MemorialDay            6
6          Mother's day            6
7         PresidentsDay            6
8         StPatricksDay            6
9         ValentinesDay            6
10          VeteransDay            5

In [95]:
con.sql("SELECT event_type_1, COUNT(event_type_1) AS event_days, MIN(date) AS first_seen, CASE WHEN COUNT(event_type_1)>40 THEN 'Large' ELSE 'Small' END AS size FROM calendar WHERE event_type_1 IS NOT NULL GROUP BY event_type_1 ORDER BY event_days DESC").df()

  event_type_1  event_days first_seen   size
0    Religious          55 2011-03-09  Large
1     National          52 2011-02-21  Large
2     Cultural          37 2011-02-14  Small
3     Sporting          18 2011-02-06  Small

In [1]:
import duckdb
con = duckdb.connect('../data/practice.duckdb')

In [10]:
con.sql("SELECT * FROM calendar LIMIT 10").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,None,None,1,0,1
5,2011-02-03,11101,Thursday,6,2,2011,d_6,NaN,NaN,None,None,1,1,1
6,2011-02-04,11101,Friday,7,2,2011,d_7,NaN,NaN,None,None,1,0,0
7,2011-02-05,11102,Saturday,1,2,2011,d_8,NaN,NaN,None,None,1,1,1
8,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,None,None,1,1,1
9,2011-02-07,11102,Monday,3,2,2011,d_10,NaN,NaN,None,None,1,1,0

In [3]:
con.sql("SELECT weekday, COUNT(weekday) AS total_days FROM calendar WHERE weekday IN('Saturday','Sunday') GROUP BY weekday").df()

    weekday  total_days
0  Saturday         282
1    Sunday         282

In [4]:
con.sql("SELECT COUNT(*) AS weekend_days FROM calendar WHERE weekday IN('Saturday','Sunday')").df()

   weekend_days
0           564

In [6]:
con.sql("SELECT month, COUNT(weekday) AS total_no_of_days FROM calendar GROUP BY month ORDER BY month").df()

    month  total_no_of_days
0       1               158
1       2               170
2       3               186
3       4               180
4       5               186
5       6               169
6       7               155
7       8               155
8       9               150
9      10               155
10     11               150
11     12               155

In [9]:
con.sql("SELECT date, event_name_1, event_type_1 FROM calendar WHERE event_name_1 IS NOT NULL ORDER BY date DESC LIMIT 5").df()

        date    event_name_1 event_type_1
0 2016-06-19    NBAFinalsEnd     Sporting
1 2016-06-07  Ramadan starts    Religious
2 2016-06-02  NBAFinalsStart     Sporting
3 2016-05-30     MemorialDay     National
4 2016-05-08    Mother's day     Cultural

In [13]:
con.sql("SELECT year, COUNT(*) AS snap_days_CA_TX FROM calendar WHERE snap_CA = 1  AND snap_TX = 1 GROUP BY year").df()

   year  snap_days_CA_TX
0  2011               66
1  2012               72
2  2013               72
3  2014               72
4  2015               72
5  2016               36

In [15]:
con.sql("SELECT date,weekday, CASE WHEN weekday IN('Saturday','Sunday') THEN 'Weekend' WHEN event_name_1 IS NOT NULL THEN 'EVENT' ELSE 'Normal' END AS day_type FROM calendar ORDER BY date LIMIT 20").df()

         date    weekday day_type
0  2011-01-29   Saturday  Weekend
1  2011-01-30     Sunday  Weekend
2  2011-01-31     Monday   Normal
3  2011-02-01    Tuesday   Normal
4  2011-02-02  Wednesday   Normal
5  2011-02-03   Thursday   Normal
6  2011-02-04     Friday   Normal
7  2011-02-05   Saturday  Weekend
8  2011-02-06     Sunday  Weekend
9  2011-02-07     Monday   Normal
10 2011-02-08    Tuesday   Normal
11 2011-02-09  Wednesday   Normal
12 2011-02-10   Thursday   Normal
13 2011-02-11     Friday   Normal
14 2011-02-12   Saturday  Weekend
15 2011-02-13     Sunday  Weekend
16 2011-02-14     Monday    EVENT
17 2011-02-15    Tuesday   Normal
18 2011-02-16  Wednesday   Normal
19 2011-02-17   Thursday   Normal

In [20]:
con.sql("SELECT event_type_1, MIN(date) FROM calendar WHERE year <2012 AND event_type_1 IS NOT NULL GROUP BY event_type_1").df()

  event_type_1  min(date)
0    Religious 2011-03-09
1     Cultural 2011-02-14
2     National 2011-02-21
3     Sporting 2011-02-06

In [23]:
con.sql("SELECT * FROM calendar LIMIT 10").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,None,None,1,0,1
5,2011-02-03,11101,Thursday,6,2,2011,d_6,NaN,NaN,None,None,1,1,1
6,2011-02-04,11101,Friday,7,2,2011,d_7,NaN,NaN,None,None,1,0,0
7,2011-02-05,11102,Saturday,1,2,2011,d_8,NaN,NaN,None,None,1,1,1
8,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,None,None,1,1,1
9,2011-02-07,11102,Monday,3,2,2011,d_10,NaN,NaN,None,None,1,1,0

In [26]:
con.sql("CREATE TABLE prices AS SELECT * FROM '../data/raw/sell_prices.csv'")

In [27]:
con.sql("SELECT * FROM prices LIMIT 10").df()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26
5     CA_1  HOBBIES_1_001     11330        8.26
6     CA_1  HOBBIES_1_001     11331        8.26
7     CA_1  HOBBIES_1_001     11332        8.26
8     CA_1  HOBBIES_1_001     11333        8.26
9     CA_1  HOBBIES_1_001     11334        8.26

In [28]:
con.sql("DESCRIBE prices").df()

  column_name column_type null   key default extra
0    store_id     VARCHAR  YES  None    None  None
1     item_id     VARCHAR  YES  None    None  None
2    wm_yr_wk      BIGINT  YES  None    None  None
3  sell_price      DOUBLE  YES  None    None  None

In [30]:
con.sql("SELECT COUNT(*) FROM prices").df()

   count_star()
0       6841121

In [33]:
con.sql("SELECT COUNT(DISTINCT store_id) FROM prices").df()

   count(DISTINCT store_id)
0                        10

In [34]:
con.sql("SELECT COUNT(DISTINCT item_id) FROM prices").df()

   count(DISTINCT item_id)
0                     3049

In [36]:
con.sql("SELECT MIN(sell_price), MAX(sell_price), AVG(sell_price) FROM prices").df()

   min(sell_price)  max(sell_price)  avg(sell_price)
0             0.01           107.32         4.410952

In [38]:
con.sql("""SELECT 
            COUNT(*) AS number_of_rows,
            COUNT(DISTINCT store_id) AS distict_stores,
            COUNT(DISTINCT item_id) AS item_id,
            MIN(sell_price) AS min_sell_price,
            MAX(sell_price) AS max_sell_price,
            AVG(sell_price) AS avg_sell_price
            FROM prices""").df()

,number_of_rows,distict_stores,item_id,min_sell_price,max_sell_price,avg_sell_price
0,6841121,10,3049,0.01,107.32,4.410952

In [44]:
con.sql("""SELECT
            prices.store_id, prices.item_id, prices.wm_yr_wk, prices.sell_price,
            calendar.date
            FROM prices
            INNER JOIN calendar
            ON prices.wm_yr_wk = calendar.wm_yr_wk
            WHERE item_id = 'HOBBIES_1_001' AND store_id = 'CA_1' LIMIT 10""").df()

  store_id        item_id  wm_yr_wk  sell_price       date
0     CA_1  HOBBIES_1_001     11325        9.58 2013-07-19
1     CA_1  HOBBIES_1_001     11326        9.58 2013-07-26
2     CA_1  HOBBIES_1_001     11327        8.26 2013-08-02
3     CA_1  HOBBIES_1_001     11328        8.26 2013-08-09
4     CA_1  HOBBIES_1_001     11329        8.26 2013-08-16
5     CA_1  HOBBIES_1_001     11330        8.26 2013-08-23
6     CA_1  HOBBIES_1_001     11331        8.26 2013-08-30
7     CA_1  HOBBIES_1_001     11332        8.26 2013-09-06
8     CA_1  HOBBIES_1_001     11333        8.26 2013-09-13
9     CA_1  HOBBIES_1_001     11334        8.26 2013-09-20

In [46]:
con.sql("""
SELECT p.store_id, p.item_id, p.wm_yr_wk, p.sell_price
FROM prices p
INNER JOIN calendar c
    ON p.wm_yr_wk = c.wm_yr_wk
WHERE p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1'
ORDER BY c.date
LIMIT 10
""").df()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11325        9.58
2     CA_1  HOBBIES_1_001     11325        9.58
3     CA_1  HOBBIES_1_001     11325        9.58
4     CA_1  HOBBIES_1_001     11325        9.58
5     CA_1  HOBBIES_1_001     11325        9.58
6     CA_1  HOBBIES_1_001     11325        9.58
7     CA_1  HOBBIES_1_001     11326        9.58
8     CA_1  HOBBIES_1_001     11326        9.58
9     CA_1  HOBBIES_1_001     11326        9.58

In [49]:
con.sql("SELECT * FROM prices LIMIT 10").df()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26
5     CA_1  HOBBIES_1_001     11330        8.26
6     CA_1  HOBBIES_1_001     11331        8.26
7     CA_1  HOBBIES_1_001     11332        8.26
8     CA_1  HOBBIES_1_001     11333        8.26
9     CA_1  HOBBIES_1_001     11334        8.26

In [56]:
con.sql("""SELECT
            c.date, c.wm_yr_wk,
            p.sell_price, p.item_id, p.store_id
            FROM calendar c
            LEFT JOIN prices p
            ON c.wm_yr_wk = p.wm_yr_wk
            AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1' ORDER BY c.date LIMIT 20""").df()

         date  wm_yr_wk  sell_price item_id store_id
0  2011-01-29     11101         NaN    None     None
1  2011-01-30     11101         NaN    None     None
2  2011-01-31     11101         NaN    None     None
3  2011-02-01     11101         NaN    None     None
4  2011-02-02     11101         NaN    None     None
5  2011-02-03     11101         NaN    None     None
6  2011-02-04     11101         NaN    None     None
7  2011-02-05     11102         NaN    None     None
8  2011-02-06     11102         NaN    None     None
9  2011-02-07     11102         NaN    None     None
10 2011-02-08     11102         NaN    None     None
11 2011-02-09     11102         NaN    None     None
12 2011-02-10     11102         NaN    None     None
13 2011-02-11     11102         NaN    None     None
14 2011-02-12     11103         NaN    None     None
15 2011-02-13     11103         NaN    None     None
16 2011-02-14     11103         NaN    None     None
17 2011-02-15     11103         NaN    None     None
18 2011-02-16     11103         NaN    None     None
19 2011-02-17     11103         NaN    None     None

In [72]:
con.sql(""" SELECT
            COUNT(c.date)
            FROM calendar c
            LEFT JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1'
                WHERE p.sell_price IS NULL""").df()

   count(c.date)
0            896

In [89]:
con.sql("""SELECT
            c.date, p.item_id
            FROM calendar c
            LEFT JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1'
                WHERE p.sell_price IS NULL
                """).df()

          date item_id
0   2011-03-19    None
1   2011-03-20    None
2   2011-03-21    None
3   2011-03-22    None
4   2011-03-23    None
..         ...     ...
891 2013-07-08    None
892 2013-07-09    None
893 2013-07-10    None
894 2013-07-11    None
895 2013-07-12    None

[896 rows x 2 columns]

In [95]:
con.sql("""SELECT
            COUNT(c.date) AS tot_date_cal,
            FROM calendar c
            LEFT JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'TX_1'
            """).df()

   tot_date_cal
0          1969

In [100]:
con.sql("""SELECT
            date, YEAR(date), MONTH(date), DAYNAME(date), DATE_TRUNC('month',date), LAST_DAY(date)
            FROM calendar
            ORDER BY date
            LIMIT 10""").df()

,date,"""year""(date)","""month""(date)",dayname(date),"date_trunc('month', date)",last_day(date)
0,2011-01-29,2011,1,Saturday,2011-01-01,2011-01-31
1,2011-01-30,2011,1,Sunday,2011-01-01,2011-01-31
2,2011-01-31,2011,1,Monday,2011-01-01,2011-01-31
3,2011-02-01,2011,2,Tuesday,2011-02-01,2011-02-28
4,2011-02-02,2011,2,Wednesday,2011-02-01,2011-02-28
5,2011-02-03,2011,2,Thursday,2011-02-01,2011-02-28
6,2011-02-04,2011,2,Friday,2011-02-01,2011-02-28
7,2011-02-05,2011,2,Saturday,2011-02-01,2011-02-28
8,2011-02-06,2011,2,Sunday,2011-02-01,2011-02-28
9,2011-02-07,2011,2,Monday,2011-02-01,2011-02-28

In [98]:
con.sql(" DESCRIBE calendar").df()

     column_name column_type null   key default extra
0           date        DATE  YES  None    None  None
1       wm_yr_wk      BIGINT  YES  None    None  None
2        weekday     VARCHAR  YES  None    None  None
3           wday      BIGINT  YES  None    None  None
4          month      BIGINT  YES  None    None  None
5           year      BIGINT  YES  None    None  None
6              d     VARCHAR  YES  None    None  None
7   event_name_1     VARCHAR  YES  None    None  None
8   event_type_1     VARCHAR  YES  None    None  None
9   event_name_2     VARCHAR  YES  None    None  None
10  event_type_2     VARCHAR  YES  None    None  None
11       snap_CA      BIGINT  YES  None    None  None
12       snap_TX      BIGINT  YES  None    None  None
13       snap_WI      BIGINT  YES  None    None  None

In [103]:
con.sql("""SELECT 
            date AS cal_date,
            date + INTERVAL 14 DAY AS day_offset_14,
            DATE_DIFF('day', DATE '2011-01-29', date) AS day_diff,
            FROM calendar
            WHERE date = '2013-07-13'""").df()

    cal_date day_offset_14  day_diff
0 2013-07-13    2013-07-27       896

In [110]:
con.sql("""SELECT 
            c.date AS cal_date, p.sell_price AS as_is_price, COALESCE(p.sell_price,0) AS null_corrected_price
            FROM calendar c
            LEFT JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1'
            WHERE c.date BETWEEN '2013-07-08'AND '2013-07-16'
            ORDER BY c.date""").df()

    cal_date  as_is_price  null_corrected_price
0 2013-07-08          NaN                  0.00
1 2013-07-09          NaN                  0.00
2 2013-07-10          NaN                  0.00
3 2013-07-11          NaN                  0.00
4 2013-07-12          NaN                  0.00
5 2013-07-13         9.58                  9.58
6 2013-07-14         9.58                  9.58
7 2013-07-15         9.58                  9.58
8 2013-07-16         9.58                  9.58

In [112]:
con.sql("""SELECT
            c.year AS year, AVG(p.sell_price) AS avg_price
            FROM calendar c
            LEFT JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                AND p.item_id = 'HOBBIES_1_001' AND p.store_id = 'CA_1'
            GROUP BY c.year
            HAVING AVG(p.sell_price) IS NOT NULL
            ORDER BY c.year""").df()

   year  avg_price
0  2013   8.367442
1  2014   8.260000
2  2015   8.260000
3  2016   8.310526

In [116]:
con.sql("SELECT * FROM calendar LIMIT 3").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,None,None,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,None,None,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,None,None,None,None,0,0,0

In [127]:
con.sql("""SELECT
            CASE WHEN p.item_id LIKE ('%HOBBIES%') THEN 'HOBBIES' WHEN p.item_id LIKE('%FOODS%') THEN 'FOODS' WHEN p.item_id LIKE ('%HOUSEHOLD%') THEN 'HOUSEHOLD' END AS item_cat,
            AVG(p.sell_price) AS avg_sell_price 
            FROM prices p
            LEFT JOIN calendar c
                ON p.wm_yr_wk = c.wm_yr_wk
                WHERE YEAR(c.date) = '2015'
                AND p.store_id = 'CA_1'
            GROUP BY item_cat
            ORDER BY avg_sell_price DESC""").df()

    item_cat  avg_sell_price
0    HOBBIES        5.590527
1  HOUSEHOLD        5.464125
2      FOODS        3.339916

In [120]:
con.sql("SELECT DISTINCT item_id FROM prices").df()

            item_id
0     HOBBIES_1_003
1     HOBBIES_1_004
2     HOBBIES_1_010
3     HOBBIES_1_012
4     HOBBIES_1_025
...             ...
3044    FOODS_3_764
3045    FOODS_3_809
3046    FOODS_3_812
3047    FOODS_3_825
3048    FOODS_3_827

[3049 rows x 1 columns]

In [132]:
con.sql("""SELECT 
            YEAR(c.date) AS year,
            COUNT(DISTINCT p.item_id) AS no_dist_prod
            FROM calendar c
            INNER JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
                WHERE p.sell_price IS NOT NULL
                AND p.store_id = 'CA_1'
            GROUP BY YEAR(c.date)
            ORDER BY year""").df()

   year  no_dist_prod
0  2011          1781
1  2012          2223
2  2013          2630
3  2014          2991
4  2015          3047
5  2016          3049

In [135]:
con.sql("""SELECT
            MONTH(c.date) AS month,
            MIN(p.sell_price) AS lowest_sell_price,
            MAX(p.sell_price) AS highest_sell_price,
            CASE WHEN lowest_sell_price = highest_sell_price THEN 'Price Stable' ELSE 'Price Changed' END AS price_move
            FROM calendar c
            INNER JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
            WHERE p.store_id = 'CA_1'
            AND p.item_id = 'FOODS_3_090'
            AND YEAR(c.date) = '2015'
            GROUP BY MONTH(c.date)
            ORDER BY month""").df()

    month  lowest_sell_price  highest_sell_price     price_move
0       1               1.48                1.48   Price Stable
1       2               1.48                1.48   Price Stable
2       3               1.48                1.48   Price Stable
3       4               1.48                1.48   Price Stable
4       5               1.48                1.48   Price Stable
5       6               1.48                1.48   Price Stable
6       7               1.48                1.48   Price Stable
7       8               1.48                1.48   Price Stable
8       9               1.48                1.48   Price Stable
9      10               1.48                1.50  Price Changed
10     11               1.50                1.50   Price Stable
11     12               1.50                1.50   Price Stable

In [136]:
con.sql("SELECT * FROM calendar")

┌────────────┬──────────┬───────────┬───────┬───────┬───────┬─────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────┬─────────┐
│    date    │ wm_yr_wk │  weekday  │ wday  │ month │ year  │    d    │ event_name_1 │ event_type_1 │ event_name_2 │ event_type_2 │ snap_CA │ snap_TX │ snap_WI │
│    date    │  int64   │  varchar  │ int64 │ int64 │ int64 │ varchar │   varchar    │   varchar    │   varchar    │   varchar    │  int64  │  int64  │  int64  │
├────────────┼──────────┼───────────┼───────┼───────┼───────┼─────────┼──────────────┼──────────────┼──────────────┼──────────────┼─────────┼─────────┼─────────┤
│ 2011-01-29 │    11101 │ Saturday  │     1 │     1 │  2011 │ d_1     │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2011-01-30 │    11101 │ Sunday    │     2 │     1 │  2011 │ d_2     │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2011-01-31 │    11101 │ Monday    │     3 │     1 │  2011 │ d_3     │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2011-02-01 │    11101 │ Tuesday   │     4 │     2 │  2011 │ d_4     │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       1 │       0 │
│ 2011-02-02 │    11101 │ Wednesday │     5 │     2 │  2011 │ d_5     │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       0 │       1 │
│ 2011-02-03 │    11101 │ Thursday  │     6 │     2 │  2011 │ d_6     │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       1 │       1 │
│ 2011-02-04 │    11101 │ Friday    │     7 │     2 │  2011 │ d_7     │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       0 │       0 │
│ 2011-02-05 │    11102 │ Saturday  │     1 │     2 │  2011 │ d_8     │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       1 │       1 │
│ 2011-02-06 │    11102 │ Sunday    │     2 │     2 │  2011 │ d_9     │ SuperBowl    │ Sporting     │ NULL         │ NULL         │       1 │       1 │       1 │
│ 2011-02-07 │    11102 │ Monday    │     3 │     2 │  2011 │ d_10    │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       1 │       0 │
│     ·      │      ·   │   ·       │     · │     · │    ·  │  ·      │  ·           │  ·           │  ·           │  ·           │       · │       · │       · │
│     ·      │      ·   │   ·       │     · │     · │    ·  │  ·      │  ·           │  ·           │  ·           │  ·           │       · │       · │       · │
│     ·      │      ·   │   ·       │     · │     · │    ·  │  ·      │  ·           │  ·           │  ·           │  ·           │       · │       · │       · │
│ 2016-06-10 │    11619 │ Friday    │     7 │     6 │  2016 │ d_1960  │ NULL         │ NULL         │ NULL         │ NULL         │       1 │       0 │       0 │
│ 2016-06-11 │    11620 │ Saturday  │     1 │     6 │  2016 │ d_1961  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       1 │       1 │
│ 2016-06-12 │    11620 │ Sunday    │     2 │     6 │  2016 │ d_1962  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       1 │       1 │
│ 2016-06-13 │    11620 │ Monday    │     3 │     6 │  2016 │ d_1963  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       1 │       0 │
│ 2016-06-14 │    11620 │ Tuesday   │     4 │     6 │  2016 │ d_1964  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       1 │
│ 2016-06-15 │    11620 │ Wednesday │     5 │     6 │  2016 │ d_1965  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       1 │       1 │
│ 2016-06-16 │    11620 │ Thursday  │     6 │     6 │  2016 │ d_1966  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2016-06-17 │    11620 │ Friday    │     7 │     6 │  2016 │ d_1967  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2016-06-18 │    11621 │ Saturday  │     1 │     6 │  2016 │ d_1968  │ NULL         │ NULL         │ NULL         │ NULL         │       0 │       0 │       0 │
│ 2016-06-19 │    11621 │ Sunday    │     2 │     6 │  2016 │ d_1969  │ NBAFinalsEnd │ Sporting     │ Father's day │ Cultural     │       0 │       0 │       0 │
└────────────┴──────────┴───────────┴───────┴───────┴───────┴─────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────┴─────────┘
  1969 rows (20 shown)                                                                                                                               14 columns

In [148]:
con.sql("""SELECT
            c.year AS year,
            p.store_id AS stores,
            COUNT(DISTINCT p.item_id) AS distinct_prod,
            ROUND(COUNT(DISTINCT p.item_id)*100.0/3049,1) AS pct_sales_prod
            FROM calendar c
            INNER JOIN prices p
                ON c.wm_yr_wk = p.wm_yr_wk
            WHERE p.sell_price IS NOT NULL
            GROUP BY (c.year,p.store_id)
            ORDER BY pct_sales_prod""").df()

    year stores  distinct_prod  pct_sales_prod
0   2011   WI_1           1430            46.9
1   2011   WI_2           1497            49.1
2   2011   CA_2           1548            50.8
3   2011   CA_4           1675            54.9
4   2011   TX_3           1732            56.8
5   2011   CA_3           1750            57.4
6   2011   WI_3           1765            57.9
7   2011   CA_1           1781            58.4
8   2011   TX_1           1791            58.7
9   2011   TX_2           1793            58.8
10  2012   CA_2           1953            64.1
11  2012   CA_4           2126            69.7
12  2012   CA_3           2199            72.1
13  2012   WI_1           2199            72.1
14  2012   TX_3           2206            72.4
15  2012   WI_2           2216            72.7
16  2012   CA_1           2223            72.9
17  2012   WI_3           2231            73.2
18  2012   TX_1           2266            74.3
19  2012   TX_2           2275            74.6
20  2013   CA_2           2350            77.1
21  2013   CA_4           2552            83.7
22  2013   TX_3           2612            85.7
23  2013   CA_3           2626            86.1
24  2013   WI_2           2629            86.2
25  2013   WI_3           2628            86.2
26  2013   CA_1           2630            86.3
27  2013   TX_1           2630            86.3
28  2013   WI_1           2638            86.5
29  2013   TX_2           2644            86.7
30  2014   CA_2           2719            89.2
31  2014   CA_4           2955            96.9
32  2014   TX_3           2974            97.5
33  2014   CA_3           2980            97.7
34  2014   WI_3           2983            97.8
35  2014   TX_2           2992            98.1
36  2014   CA_1           2991            98.1
37  2014   WI_2           2994            98.2
38  2014   WI_1           2994            98.2
39  2014   TX_1           3002            98.5
40  2015   CA_1           3047            99.9
41  2015   CA_4           3046            99.9
42  2015   CA_2           3046            99.9
43  2015   WI_2           3046            99.9
44  2015   CA_3           3046            99.9
45  2015   TX_1           3049           100.0
46  2016   WI_2           3049           100.0
47  2015   TX_3           3049           100.0
48  2016   CA_1           3049           100.0
49  2015   WI_1           3048           100.0
50  2016   TX_2           3049           100.0
51  2016   WI_3           3049           100.0
52  2016   WI_1           3049           100.0
53  2016   TX_3           3049           100.0
54  2016   CA_2           3049           100.0
55  2015   TX_2           3048           100.0
56  2016   CA_4           3049           100.0
57  2015   WI_3           3049           100.0
58  2016   CA_3           3049           100.0
59  2016   TX_1           3049           100.0

In [151]:
con.sql("CREATE TABLE sales_wide AS SELECT * FROM '../data/raw/sales_train_evaluation.csv'")

In [152]:
con.sql("SELECT COUNT(*) FROM sales_wide").df()

   count_star()
0         30490

In [156]:
con.sql("DESCRIBE sales_wide").df().head(6)

  column_name column_type null   key default extra
0          id     VARCHAR  YES  None    None  None
1     item_id     VARCHAR  YES  None    None  None
2     dept_id     VARCHAR  YES  None    None  None
3      cat_id     VARCHAR  YES  None    None  None
4    store_id     VARCHAR  YES  None    None  None
5    state_id     VARCHAR  YES  None    None  None

In [1]:
con.sql("SELECT * FROM sales_long LIMIT 10").df()

NameError: name 'con' is not defined

In [2]:

import duckdb

In [3]:
con = duckdb.connect('../data/practice.duckdb')

In [6]:
# 1. Memory settings (run once per session)
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

# 2. Wide → long
con.sql("""CREATE OR REPLACE TABLE sales_long AS
            UNPIVOT sales_wide
            ON COLUMNS('d_.*')
            INTO NAME d VALUE units""")

In [7]:
con.sql("SELECT COUNT(*) FROM sales_long").df()

   count_star()
0      59181090

In [10]:
con.sql("SELECT * FROM sales_long WHERE units>0 LIMIT 5").df()

,id,item_id,dept_id,cat_id,store_id,state_id,d,units
0,HOBBIES_1_131_CA_1_evaluation,HOBBIES_1_131,HOBBIES_1,HOBBIES,CA_1,CA,d_1344,3
1,HOBBIES_1_131_CA_1_evaluation,HOBBIES_1_131,HOBBIES_1,HOBBIES,CA_1,CA,d_1345,2
2,HOBBIES_1_131_CA_1_evaluation,HOBBIES_1_131,HOBBIES_1,HOBBIES,CA_1,CA,d_1347,2
3,HOBBIES_1_131_CA_1_evaluation,HOBBIES_1_131,HOBBIES_1,HOBBIES,CA_1,CA,d_1348,1
4,HOBBIES_1_131_CA_1_evaluation,HOBBIES_1_131,HOBBIES_1,HOBBIES,CA_1,CA,d_1351,3

In [13]:
con.sql("""WITH cat_total AS (
        SELECT 
        cat_id,
        SUM(units)
        FROM sales_long
        GROUP BY cat_id) 
        SELECT * 
        FROM cat_total
        ORDER BY cat_total""").df()

      cat_id  sum(units)
0      FOODS  45922427.0
1    HOBBIES   6240656.0
2  HOUSEHOLD  14764090.0

In [14]:
con.sql("""WITH cat_totals AS (
                SELECT
                    cat_id,
                    SUM(units) AS total_units
                FROM sales_long
                GROUP BY cat_id
            )
            SELECT *
            FROM cat_totals
            ORDER BY total_units DESC""").df()

      cat_id  total_units
0      FOODS   45922427.0
1  HOUSEHOLD   14764090.0
2    HOBBIES    6240656.0

In [16]:
con.sql("""WITH store_totals AS(
            SELECT 
            store_id AS stores,
            SUM(units) AS total_units
            FROM sales_long
            GROUP BY store_id)
            SELECT *
            FROM store_totals 
            WHERE total_units > 7000000
            ORDER BY total_units DESC""").df()

  stores  total_units
0   CA_3   11363540.0
1   CA_1    7832248.0
2   TX_2    7329642.0

In [27]:
con.sql("""WITH item_totals AS(
        SELECT
        cat_id AS cat_id,
        item_id AS item_id,
        SUM(units) AS units_total
        FROM sales_long
        GROUP BY cat_id,item_id)
        SELECT 
        cat_id,
        COUNT(*) 
        FROM item_totals 
        WHERE units_total > 20000
        GROUP BY cat_id
        ORDER BY COUNT(*) DESC""").df()

      cat_id  count_star()
0      FOODS           581
1  HOUSEHOLD           193
2    HOBBIES            70

In [32]:
con.sql("""WITH store_totals AS(
        SELECT
        state_id,
        store_id,
        SUM(units) AS total_units_sold
        FROM sales_long
        GROUP BY state_id,store_id)
        SELECT
        state_id,
        COUNT(*) AS stores_sale_more_than_6M
        FROM store_totals
        WHERE total_units_sold > 6000000
        GROUP BY state_id
        ORDER BY state_id""").df()

  state_id  stores_sale_more_than_6M
0       CA                         2
1       TX                         2
2       WI                         2

In [33]:
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [34]:
import duckdb

In [35]:
con = duckdb.connect('../data/practice.duckdb')

In [37]:
con.sql("SELECT * FROM calendar LIMIT 5").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,None,None,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,None,None,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,None,None,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,None,None,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,None,None,None,None,1,0,1

In [38]:
con.sql("SELECT * FROM sales_long LIMIT 5").df()

,id,item_id,dept_id,cat_id,store_id,state_id,d,units
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0
2,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0
3,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0
4,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0

In [39]:
con.sql("SELECT * FROM prices LIMIT 5").df()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_2_119     11452        2.97
1     CA_1  HOBBIES_2_119     11501        2.97
2     CA_1  HOBBIES_2_119     11502        2.97
3     CA_1  HOBBIES_2_119     11503        2.97
4     CA_1  HOBBIES_2_119     11504        2.97

In [49]:
con.sql("""CREATE OR REPLACE TABLE sales_daily AS SELECT 
            s.item_id AS item_id,
            s.dept_id AS dept_id,
            s.cat_id AS cat_id,
            s.store_id AS store_id,
            s.state_id AS state_id,
            c.date AS date,
            c.wm_yr_wk AS wm_yr_wk,
            s.units AS units,
            p.sell_price AS sell_price,
            s.units * p.sell_price AS revenue
            FROM sales_long s
            INNER JOIN calendar c
                ON s.d = c.d
            LEFT JOIN prices p
                ON p.wm_yr_wk = c.wm_yr_wk
                AND p.store_id = s.store_id
                AND p.item_id = s.item_id""")

In [50]:
con.sql("SELECT COUNT(*) FROM sales_daily").df()

   count_star()
0      59181090

In [70]:
con.sql("SELECT * FROM sales_daily WHERE sell_price is NULL LIMIT 15").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-02,11302,0,NaN,NaN
1,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-03,11302,0,NaN,NaN
2,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-04,11302,0,NaN,NaN
3,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-05,11302,0,NaN,NaN
4,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-06,11302,0,NaN,NaN
5,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-07,11302,0,NaN,NaN
6,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-08,11302,0,NaN,NaN
7,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-09,11303,0,NaN,NaN
8,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-10,11303,0,NaN,NaN
9,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-11,11303,0,NaN,NaN
10,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-12,11303,0,NaN,NaN
11,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-13,11303,0,NaN,NaN
12,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-14,11303,0,NaN,NaN
13,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-15,11303,0,NaN,NaN
14,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2013-02-16,11304,0,NaN,NaN

In [53]:
con.sql("""SELECT 
            cat_id AS category,
            SUM(units) AS total_unit,
            ROUND(SUM(revenue),0) AS total_revenue
            FROM sales_daily
            GROUP BY cat_id
            ORDER BY total_revenue DESC""").df()

    category  total_unit  total_revenue
0      FOODS  45922427.0    111140025.0
1  HOUSEHOLD  14764090.0     57115876.0
2    HOBBIES   6240656.0     23321644.0

In [55]:
con.sql("""SELECT
            state_id,
            store_id,
            SUM(units) AS total_units,
            ROUND(SUM(revenue),0) AS total_revenue
            FROM sales_daily
            GROUP BY state_id, store_id
            ORDER BY total_revenue DESC""").df()

  state_id store_id  total_units  total_revenue
0       CA     CA_3   11363540.0     32699138.0
1       CA     CA_1    7832248.0     22954284.0
2       TX     TX_2    7329642.0     20893002.0
3       TX     TX_3    6205940.0     18190299.0
4       WI     WI_2    6697988.0     18131985.0
5       CA     CA_2    5818395.0     17848209.0
6       WI     WI_3    6542557.0     17250126.0
7       TX     TX_1    5692823.0     16037341.0
8       WI     WI_1    5261506.0     15107434.0
9       CA     CA_4    4182534.0     12465728.0

In [66]:
con.sql("""SELECT 
            cat_id,
            ROUND(SUM(CASE WHEN units = 0 THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS pct_zero_days
            FROM sales_daily
            WHERE sell_price IS NOT NULL
            GROUP BY cat_id
            ORDER BY pct_zero_days DESC""").df()

      cat_id  pct_zero_days
0    HOBBIES           71.5
1  HOUSEHOLD           64.6
2      FOODS           51.1

In [73]:
con.sql("""SELECT
            COUNT(*) AS total_days,
            SUM(CASE WHEN sell_price IS NULL THEN 1 ELSE 0 END) AS days_no_price,
            ROUND(days_no_price/total_days*100,1) AS pct_no_price
            FROM sales_daily""").df()

   total_days  days_no_price  pct_no_price
0    59181090     12299413.0          20.8

In [74]:
con.sql("""
CREATE OR REPLACE TABLE weekly_store_sales AS
SELECT store_id,
       wm_yr_wk,
       SUM(units)   AS units,
       SUM(revenue) AS revenue
FROM sales_daily
GROUP BY store_id, wm_yr_wk
""")

In [75]:
con.sql("""
SELECT *
FROM weekly_store_sales
ORDER BY store_id, wm_yr_wk
""").df().head(10)

  store_id  wm_yr_wk    units   revenue
0     CA_1     11101  23715.0  58387.95
1     CA_1     11102  24645.0  62806.71
2     CA_1     11103  21153.0  57720.15
3     CA_1     11104  21716.0  56766.79
4     CA_1     11105  20167.0  55249.84
5     CA_1     11106  23734.0  61073.86
6     CA_1     11107  21173.0  56987.73
7     CA_1     11108  20239.0  54975.57
8     CA_1     11109  21168.0  56900.63
9     CA_1     11110  24019.0  64769.65

In [76]:
con.sql("""
SELECT COUNT(*) AS row_count,
       COUNT(DISTINCT store_id) AS stores,
       COUNT(DISTINCT wm_yr_wk) AS weeks
FROM weekly_store_sales
""").df()

   row_count  stores  weeks
0       2780      10    278

In [77]:
con.sql("""
SELECT store_id,
       wm_yr_wk,
       units,
       SUM(units) OVER (PARTITION BY store_id) AS store_total_units
FROM weekly_store_sales
WHERE store_id = 'CA_1'
ORDER BY wm_yr_wk
""").df().head(5)

  store_id  wm_yr_wk    units  store_total_units
0     CA_1     11101  23715.0          7832248.0
1     CA_1     11102  24645.0          7832248.0
2     CA_1     11103  21153.0          7832248.0
3     CA_1     11104  21716.0          7832248.0
4     CA_1     11105  20167.0          7832248.0

In [79]:
import duckdb
con = duckdb.connect('../data/practice.duckdb')
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [84]:
con.sql("""SELECT
            store_id,
            wm_yr_wk,
            units,
            SUM(units) OVER (PARTITION BY wm_yr_wk) AS units_sold_all_stores,
            ROUND(units/units_sold_all_stores*100,1) AS pct_units_sold_bystore
            FROM weekly_store_sales
            WHERE wm_yr_wk = 11101
            ORDER BY units DESC""").df()

  store_id  wm_yr_wk    units  units_sold_all_stores  pct_units_sold_bystore
0     CA_3     11101  30472.0               189942.0                    16.0
1     WI_3     11101  25972.0               189942.0                    13.7
2     CA_1     11101  23715.0               189942.0                    12.5
3     TX_2     11101  21993.0               189942.0                    11.6
4     CA_2     11101  17844.0               189942.0                     9.4
5     TX_3     11101  16936.0               189942.0                     8.9
6     TX_1     11101  15442.0               189942.0                     8.1
7     WI_2     11101  14369.0               189942.0                     7.6
8     WI_1     11101  12577.0               189942.0                     6.6
9     CA_4     11101  10622.0               189942.0                     5.6

In [89]:
con.sql("""
SELECT store_id,
        wm_yr_wk,
        units AS current_wk_units,
        LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS previous_wk_units,
        units - LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS change_units_curr_previous_wk
FROM weekly_store_sales
WHERE store_id = 'CA_1'
ORDER BY wm_yr_wk""").df()

,store_id,wm_yr_wk,current_wk_units,previous_wk_units,change_units_curr_previous_wk
0,CA_1,11101,23715.0,NaN,NaN
1,CA_1,11102,24645.0,23715.0,930.0
2,CA_1,11103,21153.0,24645.0,-3492.0
3,CA_1,11104,21716.0,21153.0,563.0
4,CA_1,11105,20167.0,21716.0,-1549.0
...,...,...,...,...,...
273,CA_1,11613,31771.0,31347.0,424.0
274,CA_1,11614,34639.0,31771.0,2868.0
275,CA_1,11615,33226.0,34639.0,-1413.0
276,CA_1,11616,34033.0,33226.0,807.0
277,CA_1,11617,12053.0,34033.0,-21980.0

In [92]:
con.sql("""
SELECT store_id,
        wm_yr_wk,
        units AS actuals,
        AVG(units) OVER 
            (PARTITION BY store_id
            ORDER BY wm_yr_wk
            ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING) AS avg_forecast_prev4
FROM weekly_store_sales
WHERE store_id = 'CA_3'
ORDER BY wm_yr_wk""").df()

    store_id  wm_yr_wk  actuals  avg_forecast_prev4
0       CA_3     11101  30472.0                 NaN
1       CA_3     11102  33726.0            30472.00
2       CA_3     11103  28088.0            32099.00
3       CA_3     11104  27939.0            30762.00
4       CA_3     11105  28246.0            30056.25
..       ...       ...      ...                 ...
273     CA_3     11613  42573.0            44365.00
274     CA_3     11614  45825.0            44044.50
275     CA_3     11615  43976.0            44011.00
276     CA_3     11616  42909.0            43802.00
277     CA_3     11617  15217.0            43820.75

[278 rows x 4 columns]

In [100]:
con.sql("""
SELECT store_id,
        wm_yr_wk,
        revenue,
        RANK() OVER (ORDER BY revenue DESC) AS rank
FROM weekly_store_sales
WHERE wm_yr_wk = 11110
ORDER BY rank""").df()

  store_id  wm_yr_wk   revenue  rank
0     CA_3     11110  86534.82     1
1     CA_1     11110  64769.65     2
2     WI_3     11110  59443.00     3
3     TX_2     11110  56593.05     4
4     CA_2     11110  50902.59     5
5     TX_3     11110  43116.46     6
6     TX_1     11110  42188.02     7
7     WI_2     11110  31273.37     8
8     WI_1     11110  30968.30     9
9     CA_4     11110  30202.79    10

In [108]:
con.sql ("""
SELECT store_id,
        wm_yr_wk,
        units,
        SUM(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cum_units_stores
FROM weekly_store_sales
WHERE wm_yr_wk BETWEEN 11101 AND 11113
AND store_id = 'TX_1'
ORDER BY wm_yr_wk""").df()

   store_id  wm_yr_wk    units  cum_units_stores
0      TX_1     11101  15442.0           15442.0
1      TX_1     11102  15788.0           31230.0
2      TX_1     11103  16248.0           47478.0
3      TX_1     11104  14819.0           62297.0
4      TX_1     11105  14934.0           77231.0
5      TX_1     11106  15765.0           92996.0
6      TX_1     11107  16653.0          109649.0
7      TX_1     11108  14645.0          124294.0
8      TX_1     11109  14893.0          139187.0
9      TX_1     11110  16022.0          155209.0
10     TX_1     11111  17021.0          172230.0
11     TX_1     11112  14814.0          187044.0
12     TX_1     11113  13303.0          200347.0

In [112]:
con.sql("""
SELECT store_id,
        wm_yr_wk,
        units,
        LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS naive_forecast,
        units - LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS forecast_error
FROM weekly_store_sales
WHERE store_id = 'CA_2'
ORDER BY wm_yr_wk""").df()

    store_id  wm_yr_wk    units  naive_forecast  forecast_error
0       CA_2     11101  17844.0             NaN             NaN
1       CA_2     11102  17948.0         17844.0           104.0
2       CA_2     11103  16185.0         17948.0         -1763.0
3       CA_2     11104  16268.0         16185.0            83.0
4       CA_2     11105  16012.0         16268.0          -256.0
..       ...       ...      ...             ...             ...
273     CA_2     11613  31080.0         30024.0          1056.0
274     CA_2     11614  33708.0         31080.0          2628.0
275     CA_2     11615  32369.0         33708.0         -1339.0
276     CA_2     11616  33995.0         32369.0          1626.0
277     CA_2     11617  13734.0         33995.0        -20261.0

[278 rows x 5 columns]

In [116]:
con.sql("""WITH naive_fcst_error AS(
SELECT store_id,
        wm_yr_wk,
        units,
        LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS naive_fcst,
        units - LAG(units) OVER (PARTITION BY store_id ORDER BY wm_yr_wk) AS error 
FROM weekly_store_sales)
SELECT store_id,
        SUM(units) AS agg_actuals,
        SUM(naive_fcst) AS agg_naive_FCST,
        ROUND(SUM(ABS(naive_fcst - units))/SUM(units)*100,1) AS wmape,
        ROUND(SUM(naive_fcst - units)/SUM(units)*100,1) AS bias
FROM naive_fcst_error
WHERE naive_fcst IS NOT NULL
AND wm_yr_wk != 11617
GROUP BY store_id
ORDER BY wmape DESC""").df()

  store_id  agg_actuals  agg_naive_FCST  wmape  bias
0     WI_2    6673338.0       6648737.0   13.8  -0.4
1     WI_3    6507309.0       6503718.0   11.0  -0.1
2     TX_1    5668590.0       5658668.0    6.3  -0.2
3     TX_3    6179318.0       6166935.0    6.2  -0.2
4     CA_3   11317851.0      11305414.0    6.2  -0.1
5     CA_1    7796480.0       7786162.0    5.9  -0.1
6     TX_2    7297630.0       7290253.0    5.5  -0.1
7     WI_1    5238873.0       5223074.0    5.2  -0.3
8     CA_4    4165169.0       4155711.0    4.2  -0.2
9     CA_2    5786817.0       5770666.0    4.1  -0.3

In [115]:
con.sql("SELECT * FROM weekly_store_sales ORDER BY wm_yr_wk DESC").df()

     store_id  wm_yr_wk    units   revenue
0        WI_1     11617  10056.0  29947.00
1        TX_3     11617   9686.0  32860.77
2        WI_2     11617  10281.0  29841.76
3        CA_3     11617  15217.0  51125.36
4        TX_2     11617  10019.0  32844.62
...       ...       ...      ...       ...
2775     WI_1     11101  12577.0  29203.79
2776     CA_1     11101  23715.0  58387.95
2777     WI_2     11101  14369.0  33947.26
2778     TX_3     11101  16936.0  41865.50
2779     CA_3     11101  30472.0  74800.93

[2780 rows x 4 columns]

In [118]:
con.sql("SELECT * FROM sales_daily LIMIT 2").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,HOUSEHOLD_1_264,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,2014-01-12,11351,0,6.97,0.0
1,HOUSEHOLD_1_264,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,2014-01-13,11351,0,6.97,0.0

In [128]:
con.sql("""CREATE OR REPLACE TABLE item_revenue_52w AS
SELECT item_id,
        dept_id,
        cat_id,
        SUM(revenue) AS total_revenue
FROM sales_daily
WHERE date BETWEEN '2015-05-25' AND '2016-05-22'
GROUP BY item_id,dept_id,cat_id""")

In [127]:
con.sql("SELECT * FROM item_revenue_52w LIMIT 15").df()

            item_id      dept_id     cat_id  total_revenue
0       FOODS_2_015      FOODS_2      FOODS        5365.54
1       FOODS_2_018      FOODS_2      FOODS       39248.54
2       FOODS_2_026      FOODS_2      FOODS       17860.52
3       FOODS_2_032      FOODS_2      FOODS        9715.66
4       FOODS_2_040      FOODS_2      FOODS        5882.00
5       FOODS_2_047      FOODS_2      FOODS       13586.47
6       FOODS_2_061      FOODS_2      FOODS       12610.00
7       FOODS_2_066      FOODS_2      FOODS       14932.06
8       FOODS_2_067      FOODS_2      FOODS        5622.16
9   HOUSEHOLD_2_419  HOUSEHOLD_2  HOUSEHOLD        2320.25
10  HOUSEHOLD_2_433  HOUSEHOLD_2  HOUSEHOLD        2951.87
11  HOUSEHOLD_2_446  HOUSEHOLD_2  HOUSEHOLD        7135.66
12  HOUSEHOLD_2_465  HOUSEHOLD_2  HOUSEHOLD       17772.80
13    HOBBIES_1_157    HOBBIES_1    HOBBIES       16841.04
14    HOBBIES_1_160    HOBBIES_1    HOBBIES       25439.54

In [129]:
con.sql("""
SELECT COUNT(*) AS items,
       SUM(total_revenue) AS revenue_52w,
       SUM(CASE WHEN total_revenue IS NULL OR total_revenue = 0 THEN 1 ELSE 0 END) AS items_no_revenue
FROM item_revenue_52w
""").df()

   items  revenue_52w  items_no_revenue
0   3049  45041697.91               0.0

In [130]:
con.sql("SELECT * FROM item_revenue_52w LIMIT 2").df()

         item_id    dept_id   cat_id  total_revenue
0  HOBBIES_1_130  HOBBIES_1  HOBBIES        4651.92
1  HOBBIES_1_134  HOBBIES_1  HOBBIES       37422.90

In [153]:
con.sql("""
SELECT item_id,
        dept_id,
        cat_id,
        total_revenue,
        ROW_NUMBER() OVER (ORDER BY total_revenue DESC, item_id) AS rank_revenue,
        SUM(total_revenue) OVER (ORDER BY total_revenue DESC,item_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_tot_rev,
        SUM(total_revenue) OVER () AS tot_rev_all,
        ROUND(running_tot_rev/tot_rev_all*100.0,1) AS cum_perc_rev,
        CASE WHEN cum_perc_rev <= 80 THEN 'A'WHEN cum_perc_rev <= 95 THEN 'B' ELSE 'C' END AS abc_rev
        FROM item_revenue_52w
        ORDER BY total_revenue DESC""").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,running_tot_rev,tot_rev_all,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,498941.76,45041697.91,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,964044.56,45041697.91,2.1,A
2,HOBBIES_1_158,HOBBIES_1,HOBBIES,429794.94,3,1393839.50,45041697.91,3.1,A
3,FOODS_1_096,FOODS_1,FOODS,281430.75,4,1675270.25,45041697.91,3.7,A
4,FOODS_3_586,FOODS_3,FOODS,276595.20,5,1951865.45,45041697.91,4.3,A
...,...,...,...,...,...,...,...,...,...
3044,HOBBIES_2_030,HOBBIES_2,HOBBIES,245.91,3045,45040801.05,45041697.91,100.0,C
3045,HOBBIES_2_025,HOBBIES_2,HOBBIES,240.00,3046,45041041.05,45041697.91,100.0,C
3046,HOBBIES_2_073,HOBBIES_2,HOBBIES,238.50,3047,45041279.55,45041697.91,100.0,C
3047,HOBBIES_1_112,HOBBIES_1,HOBBIES,210.36,3048,45041489.91,45041697.91,100.0,C
3048,HOBBIES_2_047,HOBBIES_2,HOBBIES,208.00,3049,45041697.91,45041697.91,100.0,C

In [154]:
con.sql("""
WITH item_running AS (
    SELECT item_id,
           dept_id,
           cat_id,
           total_revenue,
           ROW_NUMBER() OVER (ORDER BY total_revenue DESC, item_id) AS rank_revenue,
           SUM(total_revenue) OVER (ORDER BY total_revenue DESC, item_id
                                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_tot_rev,
           SUM(total_revenue) OVER () AS tot_rev_all
    FROM item_revenue_52w
)
SELECT item_id,
       dept_id,
       cat_id,
       total_revenue,
       rank_revenue,
       ROUND(running_tot_rev * 100.0 / tot_rev_all, 1) AS cum_perc_rev,
       CASE WHEN running_tot_rev * 100.0 / tot_rev_all <= 80 THEN 'A'
            WHEN running_tot_rev * 100.0 / tot_rev_all <= 95 THEN 'B'
            ELSE 'C'
       END AS abc_rev
FROM item_running
ORDER BY rank_revenue
""").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A
2,HOBBIES_1_158,HOBBIES_1,HOBBIES,429794.94,3,3.1,A
3,FOODS_1_096,FOODS_1,FOODS,281430.75,4,3.7,A
4,FOODS_3_586,FOODS_3,FOODS,276595.20,5,4.3,A
...,...,...,...,...,...,...,...
3044,HOBBIES_2_030,HOBBIES_2,HOBBIES,245.91,3045,100.0,C
3045,HOBBIES_2_025,HOBBIES_2,HOBBIES,240.00,3046,100.0,C
3046,HOBBIES_2_073,HOBBIES_2,HOBBIES,238.50,3047,100.0,C
3047,HOBBIES_1_112,HOBBIES_1,HOBBIES,210.36,3048,100.0,C
3048,HOBBIES_2_047,HOBBIES_2,HOBBIES,208.00,3049,100.0,C

In [155]:
con.sql("""CREATE OR REPLACE TABLE item_abc AS
WITH item_running AS (
    SELECT item_id,
           dept_id,
           cat_id,
           total_revenue,
           ROW_NUMBER() OVER (ORDER BY total_revenue DESC, item_id) AS rank_revenue,
           SUM(total_revenue) OVER (ORDER BY total_revenue DESC, item_id
                                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_tot_rev,
           SUM(total_revenue) OVER () AS tot_rev_all
    FROM item_revenue_52w
)
SELECT item_id,
       dept_id,
       cat_id,
       total_revenue,
       rank_revenue,
       ROUND(running_tot_rev * 100.0 / tot_rev_all, 1) AS cum_perc_rev,
       CASE WHEN running_tot_rev * 100.0 / tot_rev_all <= 80 THEN 'A'
            WHEN running_tot_rev * 100.0 / tot_rev_all <= 95 THEN 'B'
            ELSE 'C'
       END AS abc_rev
FROM item_running
""")

In [158]:
con.sql("SELECT COUNT(*) FROM item_abc").df()

   count_star()
0          3049

In [159]:
con.sql("""SELECT * FROM item_abc LIMIT 2""").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A

In [170]:
con.sql("""SELECT abc_rev,
                    COUNT(*) AS no_of_items,
                    ROUND(COUNT(*)/3049*100,1) AS perc_items,
                    SUM(total_revenue) AS total_rev_class_level,
                    ROUND(SUM(total_revenue)/ SUM(SUM(total_revenue)) OVER()*100.0,1) AS perc_tot_rev
            FROM item_abc
            GROUP BY abc_rev
            ORDER BY abc_rev""").df()

  abc_rev  no_of_items  perc_items  total_rev_class_level  perc_tot_rev
0       A         1318        43.2            36028172.28          80.0
1       B          943        30.9             6760602.99          15.0
2       C          788        25.8             2252922.64           5.0

In [172]:
con.sql("""CREATE OR REPLACE TABLE item_weekly_units_52w AS
SELECT item_id,
        wm_yr_wk,
        SUM(units) AS total_units
FROM sales_daily 
WHERE date BETWEEN '2015-05-23' AND '2016-05-20'
GROUP BY wm_yr_wk, item_id""")

In [171]:
con.sql("""SELECT * FROM sales_daily LIMIT 2""").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,HOUSEHOLD_1_126,HOUSEHOLD_1,HOUSEHOLD,CA_2,CA,2015-06-24,11521,1,8.96,8.96
1,HOUSEHOLD_1_126,HOUSEHOLD_1,HOUSEHOLD,CA_2,CA,2015-06-25,11521,0,8.96,0.00

In [178]:
con.sql("""SELECT * FROM item_weekly_units_52w LIMIT 2""").df()

       item_id  wm_yr_wk  total_units
0  FOODS_3_057     11548         29.0
1  FOODS_3_057     11550         43.0

In [179]:
con.sql("""CREATE OR REPLACE TABLE item_xyz AS
SELECT item_id,
            AVG(total_units) AS avg_weekly_units,
            STDDEV(total_units) AS std_dev_units,
            ROUND(STDDEV(total_units)/AVG(total_units),2) AS cv_items,
            CASE 
            WHEN STDDEV(total_units)/AVG(total_units) <= 0.5 THEN 'X'
            WHEN STDDEV(total_units)/AVG(total_units) <= 1.0 THEN 'Y'
                ELSE 'Z' END AS xyz_items
            FROM item_weekly_units_52w
            GROUP BY item_id""")

In [180]:
con.sql("""SELECT * FROM item_xyz LIMIT 5""").df()

       item_id  avg_weekly_units  std_dev_units  cv_items xyz_items
0  FOODS_2_110         91.153846      34.098694      0.37         X
1  FOODS_2_288         58.519231      31.262011      0.53         Y
2  FOODS_2_304        115.346154      17.393806      0.15         X
3  FOODS_2_307        145.557692      36.209853      0.25         X
4  FOODS_2_321         59.730769      12.173767      0.20         X

In [184]:
con.sql ("""SELECT xyz_items,
        COUNT(*) AS no_of_items,
        FROM item_xyz
        GROUP BY xyz_items""").df()

  xyz_items  no_of_items
0         X         2364
1         Y          584
2         Z          101

In [185]:
import duckdb
con = duckdb.connect('../data/practice.duckdb')
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [190]:
con.sql ("""SELECT xyz_items,
        COUNT(*) AS no_of_items,
        ROUND(COUNT(*)*100.0/SUM(COUNT(*)) OVER(),1) AS perc_of_items
        FROM item_xyz
        GROUP BY xyz_items
        ORDER BY xyz_items""").df()

  xyz_items  no_of_items  perc_of_items
0         X         2364           77.5
1         Y          584           19.2
2         Z          101            3.3

In [191]:
import duckdb
con = duckdb.connect('../data/practice.duckdb')
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [192]:
con.sql("SELECT * FROM item_abc LIMIT 2").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A

In [193]:
con.sql("SELECT * FROM item_xyz LIMIT 2").df()

       item_id  avg_weekly_units  std_dev_units  cv_items xyz_items
0  FOODS_2_110         91.153846      34.098694      0.37         X
1  FOODS_2_288         58.519231      31.262011      0.53         Y

In [203]:
con.sql("""SELECT a.abc_rev || x.xyz_items AS abc_xyz_class,
                COUNT(*) AS no_of_items,
                ROUND(COUNT(*)*100.0/SUM(COUNT(*)) OVER (),1) AS perc_items,
                ROUND(SUM(a.total_revenue)*100.0/SUM(SUM(a.total_revenue)) OVER (),1) AS perc_rev
                FROM item_abc a
                INNER JOIN item_xyz x
                    ON a.item_id = x.item_id
                GROUP BY abc_xyz_class
                ORDER BY abc_xyz_class""").df()

  abc_xyz_class  no_of_items  perc_items  perc_rev
0            AX         1119        36.7      68.0
1            AY          168         5.5      10.4
2            AZ           31         1.0       1.5
3            BX          712        23.4      11.4
4            BY          203         6.7       3.1
5            BZ           28         0.9       0.4
6            CX          533        17.5       3.5
7            CY          213         7.0       1.3
8            CZ           42         1.4       0.2

In [206]:
con.sql("SELECT * FROM item_weekly_units_52w LIMIT 5").df()

       item_id  wm_yr_wk  total_units
0  FOODS_3_057     11548         29.0
1  FOODS_3_057     11550         43.0
2  FOODS_3_060     11525         53.0
3  FOODS_3_060     11535         47.0
4  FOODS_3_061     11525         41.0

In [209]:
con.sql("""SELECT
            item_id,
            total_units,
            LAG(total_units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) AS naive_fcst,
            LAG(total_units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) - total_units AS error,
            STDDEV(total_units) AS std_dev_units,
            STDDEV(LAG(total_units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) - total_units) AS std_dev_error,
            ROUND(STDDEV(total_units)/STDDEV(LAG(total_units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) - total_units),2) AS ratio_error
            FROM item_weekly_units_52w
            GROUP BY item_id""").df()

BinderException: Binder Error: aggregate function calls cannot contain window function calls

In [210]:
con.sql("""
WITH weekly_error AS (
    SELECT item_id,
           wm_yr_wk,
           total_units,
           LAG(total_units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) AS naive_fcst
    FROM item_weekly_units_52w
)
SELECT item_id,
       ROUND(STDDEV(total_units), 2) AS std_dev_demand,
       ROUND(STDDEV(naive_fcst - total_units), 2) AS std_dev_error,
       ROUND(STDDEV(naive_fcst - total_units) / STDDEV(total_units), 2) AS ratio_error_to_demand
FROM weekly_error
WHERE naive_fcst IS NOT NULL
GROUP BY item_id
ORDER BY ratio_error_to_demand DESC
""").df()

              item_id  std_dev_demand  std_dev_error  ratio_error_to_demand
0     HOUSEHOLD_2_233            2.80           4.68                   1.67
1     HOUSEHOLD_2_017            4.66           7.73                   1.66
2     HOUSEHOLD_2_457            6.33          10.48                   1.65
3       HOBBIES_1_328            3.37           5.53                   1.64
4         FOODS_2_161            4.93           8.11                   1.64
...               ...             ...            ...                    ...
3044      FOODS_3_307          150.50          37.16                   0.25
3045      FOODS_3_039          145.86          35.35                   0.24
3046      FOODS_3_238           91.45          21.65                   0.24
3047      FOODS_3_572          266.58          46.82                   0.18
3048      FOODS_3_263          297.37          53.86                   0.18

[3049 rows x 4 columns]

In [211]:
con.sql("SELECT * FROM item_abc LIMIT 2").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A

In [212]:
con.sql("SELECT * FROM item_xyz LIMIT 2").df()

       item_id  avg_weekly_units  std_dev_units  cv_items xyz_items
0  FOODS_2_110         91.153846      34.098694      0.37         X
1  FOODS_2_288         58.519231      31.262011      0.53         Y

In [222]:
con.sql("""SELECT
            a.item_id,
            a.abc_rev,
            x.avg_weekly_units,
            CASE WHEN a.abc_rev = 'A' THEN 2.05 WHEN a.abc_rev = 'B' THEN 1.65 ELSE 1.28 END AS z_factor,
            x.std_dev_units,
            ROUND(z_factor * x.std_dev_units * SQRT(2),0) AS safety_stock,
            ROUND(z_factor * x.std_dev_units * SQRT(2),0)*7/x.avg_weekly_units,2) AS days_of_cov
            FROM item_abc a
            INNER JOIN item_xyz x
                ON a.item_id = x.item_id
            ORDER BY safety_stock DESC""").df()

ParserException: Parser Error: syntax error at or near ")"

LINE 8: ...(z_factor * x.std_dev_units * SQRT(2),0)*7/x.avg_weekly_units,2) AS days_of_cov
                                                                          ^

In [221]:
con.sql("""WITH item_z AS (
        SELECT a.item_id,
        a.abc_rev,
        x.avg_weekly_units,
        x.std_dev_units,
        CASE WHEN a.abc_rev ='A' THEN 2.05 WHEN a.abc_rev = 'B' THEN 1.65 ELSE 1.28 END AS z_factor
        FROM item_abc a
        INNER JOIN item_xyz x
            ON a.item_id = x.item_id)   
        SELECT 
        item_id,
        abc_rev,
        avg_weekly_units,
        std_dev_units,
        z_factor,
        ROUND(z_factor * std_dev_units * SQRT(2),0) AS safety_stock,
        ROUND(z_factor * std_dev_units * SQRT(2)*7/ avg_weekly_units,1) AS doh_coverage
        FROM item_z
        ORDER BY safety_stock DESC""").df()

,item_id,abc_rev,avg_weekly_units,std_dev_units,z_factor,safety_stock,doh_coverage
0,FOODS_3_090,A,3323.403846,1435.075570,2.05,4160.0,8.8
1,FOODS_3_808,A,664.153846,616.038176,2.05,1786.0,18.8
2,FOODS_2_360,A,718.057692,551.288132,2.05,1598.0,15.6
3,FOODS_3_329,A,571.211538,496.762394,2.05,1440.0,17.6
4,FOODS_3_202,A,1146.057692,484.619091,2.05,1405.0,8.6
...,...,...,...,...,...,...,...
3044,HOBBIES_2_016,C,4.615385,2.302206,1.28,4.0,6.3
3045,HOUSEHOLD_2_065,C,4.384615,2.078403,1.28,4.0,6.0
3046,HOUSEHOLD_2_005,C,5.461538,2.388383,1.28,4.0,5.5
3047,HOUSEHOLD_2_276,C,7.307692,2.355956,1.28,4.0,4.1
3048,HOUSEHOLD_2_147,C,4.596154,1.912391,1.28,3.0,5.3

In [223]:
con.sql("""WITH item_z AS (
        SELECT a.item_id,
        a.abc_rev,
        x.avg_weekly_units,
        x.std_dev_units,
        CASE WHEN a.abc_rev ='A' THEN 2.05 WHEN a.abc_rev = 'B' THEN 1.65 ELSE 1.28 END AS z_factor
        FROM item_abc a
        INNER JOIN item_xyz x
            ON a.item_id = x.item_id)   
        SELECT 
        item_id,
        abc_rev,
        avg_weekly_units,
        std_dev_units,
        z_factor,
        ROUND(z_factor * std_dev_units * SQRT(2),0) AS safety_stock,
        ROUND(z_factor * std_dev_units * SQRT(2)*7/ avg_weekly_units,1) AS doh_coverage
        FROM item_z
        ORDER BY doh_coverage DESC""").df()

,item_id,abc_rev,avg_weekly_units,std_dev_units,z_factor,safety_stock,doh_coverage
0,FOODS_3_441,A,64.750000,172.226581,2.05,499.0,54.0
1,HOBBIES_1_335,C,5.038462,19.131087,1.28,35.0,48.1
2,FOODS_3_444,A,176.826923,398.045505,2.05,1154.0,45.7
3,FOODS_3_069,A,107.326923,230.645022,2.05,669.0,43.6
4,FOODS_2_255,A,130.826923,254.142751,2.05,737.0,39.4
...,...,...,...,...,...,...,...
3044,FOODS_3_458,A,673.653846,63.295722,2.05,184.0,1.9
3045,FOODS_3_697,A,433.288462,40.743741,2.05,118.0,1.9
3046,FOODS_3_108,B,179.250000,19.214858,1.65,45.0,1.8
3047,HOUSEHOLD_1_053,A,203.423077,16.961717,2.05,49.0,1.7
3048,FOODS_3_756,A,533.076923,45.599211,2.05,132.0,1.7

In [230]:
con.sql("""SELECT * FROM calendar WHERE event_type_1 IS NOT NULL LIMIT 2""").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-02-06,11102,Sunday,2,2,2011,d_9,SuperBowl,Sporting,None,None,1,1,1
1,2011-02-14,11103,Monday,3,2,2011,d_17,ValentinesDay,Cultural,None,None,0,0,1

In [226]:
con.sql("""SELECT * FROM prices LIMIT 2""").df()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_2_119     11452        2.97
1     CA_1  HOBBIES_2_119     11501        2.97

In [227]:
con.sql("""SELECT * FROM sales_daily LIMIT 2""").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-15,11607,0,1.12,0.0
1,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-16,11607,0,1.12,0.0

In [236]:
con.sql("""CREATE OR REPLACE TABLE ml_base_ca3 AS
            SELECT s.item_id,
            s.dept_id,
            s.cat_id,
            s.wm_yr_wk,
            SUM(s.units),
            p.sell_price,
            SUM(CASE WHEN c.event_name_1 IS NULL THEN 0 ELSE 1 END) AS no_of_event_days,
            SUM(c.snap_CA) AS no_of_snap_days
            FROM sales_daily s
            INNER JOIN prices p
                ON s.item_id = p.item_id
            INNER JOIN calendar c
                ON s.wm_yr_wk = c.wm_yr_wk
            WHERE s.store_id = 'CA_3'
            GROUP BY s.wm_yr_wk, s.item_id, s.dept_id, s.cat_id""")

BinderException: Binder Error: column "units" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(units)" if the exact value of "units" is not important.

LINE 6:             s.units,
                    ^

In [237]:
con.sql("""
CREATE OR REPLACE TABLE ml_base_ca3 AS
SELECT s.item_id,
       s.dept_id,
       s.cat_id,
       s.wm_yr_wk,
       SUM(s.units) AS units,
       MAX(s.sell_price) AS sell_price,
       SUM(CASE WHEN c.event_name_1 IS NOT NULL THEN 1 ELSE 0 END) AS event_days,
       SUM(c.snap_CA) AS snap_days
FROM sales_daily s
INNER JOIN calendar c
    ON s.date = c.date
WHERE s.store_id = 'CA_3'
  AND s.sell_price IS NOT NULL
  AND s.wm_yr_wk <> 11617
GROUP BY s.item_id, s.dept_id, s.cat_id, s.wm_yr_wk
""")

In [238]:
con.sql("""
SELECT (SELECT SUM(units) FROM ml_base_ca3) AS units_new_table,
       (SELECT SUM(units) FROM sales_daily
        WHERE store_id = 'CA_3' AND sell_price IS NOT NULL AND wm_yr_wk <> 11617) AS units_source
""").df()

   units_new_table  units_source
0       11348323.0    11348323.0

In [239]:
con.sql("SELECT * FROM ml_base_ca3 LIMIT 10").df()

,item_id,dept_id,cat_id,wm_yr_wk,units,sell_price,event_days,snap_days
0,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11333,0.0,4.43,0.0,4.0
1,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11335,0.0,3.97,0.0,0.0
2,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11416,5.0,4.78,0.0,0.0
3,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11446,7.0,4.78,0.0,0.0
4,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11525,6.0,4.78,1.0,0.0
5,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11526,10.0,4.78,0.0,0.0
6,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11531,6.0,4.78,0.0,4.0
7,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11604,7.0,4.78,0.0,0.0
8,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11606,6.0,4.78,0.0,6.0
9,HOUSEHOLD_2_232,HOUSEHOLD_2,HOUSEHOLD,11608,6.0,4.78,1.0,0.0

In [258]:
con.sql("""CREATE OR REPLACE TABLE ml_features_ca3 AS
            SELECT item_id,
            dept_id,
            cat_id,
            wm_yr_wk,
            units,
            sell_price,
            event_days,
            snap_days,
            wm_yr_wk % 100 AS week_of_yr,
            LAG(units,1) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) AS units_1wk_pr,
            LAG(units,2) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) AS units_2wk_pr,
            LAG(units,52) OVER (PARTITION BY item_id ORDER BY wm_yr_wk) AS units_52wk_pr,
            AVG(units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING) AS avg_units_pr_4wk,
            AVG(units) OVER (PARTITION BY item_id ORDER BY wm_yr_wk ROWS BETWEEN 13 PRECEDING AND 1 PRECEDING) AS avg_units_pr_13wk,
            ROUND((sell_price - LAG(sell_price,1) OVER (PARTITION BY item_id ORDER BY wm_yr_wk))*100/LAG(sell_price,1) OVER (PARTITION BY item_id ORDER BY wm_yr_wk),1) AS price_change_pct_wow
            FROM ml_base_ca3""")

In [260]:
con.sql("""SELECT * FROM ml_features_ca3 WHERE item_id = 'FOODS_3_090' ORDER BY wm_yr_wk""").df()

,item_id,dept_id,cat_id,wm_yr_wk,units,sell_price,event_days,snap_days,week_of_yr,units_1wk_pr,units_2wk_pr,units_52wk_pr,avg_units_pr_4wk,avg_units_pr_13wk,price_change_pct_wow
0,FOODS_3_090,FOODS_3,FOODS,11101,970.0,1.25,0.0,4.0,1,NaN,NaN,NaN,NaN,NaN,NaN
1,FOODS_3_090,FOODS_3,FOODS,11102,481.0,1.25,1.0,6.0,2,970.0,NaN,NaN,970.000000,970.000000,0.0
2,FOODS_3_090,FOODS_3,FOODS,11103,0.0,1.25,1.0,0.0,3,481.0,970.0,NaN,725.500000,725.500000,0.0
3,FOODS_3_090,FOODS_3,FOODS,11104,0.0,1.25,1.0,0.0,4,0.0,481.0,NaN,483.666667,483.666667,0.0
4,FOODS_3_090,FOODS_3,FOODS,11105,0.0,1.25,0.0,4.0,5,0.0,0.0,NaN,362.750000,362.750000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,FOODS_3_090,FOODS_3,FOODS,11612,856.0,1.60,0.0,0.0,12,782.0,703.0,801.0,785.750000,736.923077,0.0
273,FOODS_3_090,FOODS_3,FOODS,11613,927.0,1.60,0.0,0.0,13,856.0,782.0,973.0,812.750000,759.230769,0.0
274,FOODS_3_090,FOODS_3,FOODS,11614,751.0,1.60,3.0,6.0,14,927.0,856.0,1093.0,817.000000,778.384615,0.0
275,FOODS_3_090,FOODS_3,FOODS,11615,935.0,1.60,1.0,4.0,15,751.0,927.0,774.0,829.000000,785.384615,0.0
276,FOODS_3_090,FOODS_3,FOODS,11616,758.0,1.60,0.0,0.0,16,935.0,751.0,9.0,867.250000,799.769231,0.0

In [261]:
con.sql("SELECT * FROM item_abc LIMIT 2").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A

In [262]:
con.sql("SELECT * FROM item_xyz LIMIT 2").df()

       item_id  avg_weekly_units  std_dev_units  cv_items xyz_items
0  FOODS_2_110         91.153846      34.098694      0.37         X
1  FOODS_2_288         58.519231      31.262011      0.53         Y

In [272]:
con.sql("""CREATE OR REPLACE VIEW v_abc_xyz_matrix AS
            SELECT a.abc_rev || x.xyz_items AS segment,
            COUNT(*) AS total_items,
            SUM(a.total_revenue) AS segment_revenue,
            ROUND(COUNT(*)*100.0/SUM(COUNT(*)) OVER (),2) AS perc_items,
            ROUND(SUM(a.total_revenue)*100.0/SUM(SUM(a.total_revenue)) OVER(),2) perc_revenue
            FROM item_abc a
            INNER JOIN item_xyz x
                ON a.item_id = x.item_id
            GROUP BY a.abc_rev || x.xyz_items
            ORDER BY segment""")

In [273]:
con.sql("SELECT * FROM v_abc_xyz_matrix").df()

  segment  total_items  segment_revenue  perc_items  perc_revenue
0      AX         1119      30637512.82       36.70         68.02
1      AY          168       4693484.65        5.51         10.42
2      AZ           31        697174.81        1.02          1.55
3      BX          712       5139691.39       23.35         11.41
4      BY          203       1418265.92        6.66          3.15
5      BZ           28        202645.68        0.92          0.45
6      CX          533       1597245.05       17.48          3.55
7      CY          213        564660.56        6.99          1.25
8      CZ           42         91017.03        1.38          0.20

In [275]:
con.sql(""" SELECT * 
            FROM v_abc_xyz_matrix
            WHERE perc_revenue > 5
            ORDER BY perc_revenue DESC""").df()

  segment  total_items  segment_revenue  perc_items  perc_revenue
0      AX         1119      30637512.82       36.70         68.02
1      BX          712       5139691.39       23.35         11.41
2      AY          168       4693484.65        5.51         10.42

In [277]:
con.sql("SELECT * FROM sales_daily LIMIT 5").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,FOODS_3_055,FOODS_3,FOODS,CA_1,CA,2013-12-13,11346,0,3.48,0.0
1,FOODS_3_055,FOODS_3,FOODS,CA_1,CA,2013-12-14,11347,0,3.48,0.0
2,FOODS_3_055,FOODS_3,FOODS,CA_1,CA,2013-12-15,11347,0,3.48,0.0
3,FOODS_3_055,FOODS_3,FOODS,CA_1,CA,2013-12-16,11347,0,3.48,0.0
4,FOODS_3_055,FOODS_3,FOODS,CA_1,CA,2013-12-17,11347,0,3.48,0.0

In [284]:
con.sql("""SELECT
            store_id,
            SUM(revenue) AS tot_revenue
            FROM sales_daily
            WHERE date BETWEEN '2015-01-01' AND '2015-12-31'
            GROUP BY store_id
            ORDER BY tot_revenue DESC""").df()

  store_id   tot_revenue
0     CA_3  7.054106e+06
1     CA_1  5.058087e+06
2     TX_3  4.395219e+06
3     WI_2  4.298561e+06
4     TX_2  4.290981e+06
5     CA_2  3.906888e+06
6     WI_1  3.789069e+06
7     TX_1  3.535360e+06
8     WI_3  3.305906e+06
9     CA_4  2.782281e+06

In [288]:
con.sql("""SELECT 
        item_id,
        SUM(units) AS tot_unit_sold
        FROM sales_daily
        WHERE store_id = 'CA_1'
        GROUP BY item_id
        HAVING tot_unit_sold > 10000
        ORDER BY tot_unit_sold DESC""").df()

           item_id  tot_unit_sold
0      FOODS_3_090       128855.0
1      FOODS_3_586        88846.0
2      FOODS_3_252        76055.0
3      FOODS_3_120        63107.0
4      FOODS_3_714        54617.0
..             ...            ...
137    FOODS_3_594        10231.0
138    FOODS_3_474        10212.0
139    FOODS_3_688        10168.0
140  HOBBIES_1_067        10067.0
141    FOODS_3_113        10054.0

[142 rows x 2 columns]

In [290]:
con.sql("""SELECT 
            store_id,
            SUM(revenue),
            SUM(revenue)*100.0/SUM(SUM(revenue)) OVER() AS perc_revenue_store
            FROM sales_daily
            GROUP BY store_id
            ORDER BY SUM(revenue)*100.0/SUM(SUM(revenue)) OVER()""").df()

  store_id  sum(revenue)  perc_revenue_store
0     CA_4  1.246573e+07            6.506884
1     WI_1  1.510743e+07            7.885806
2     TX_1  1.603734e+07            8.371201
3     WI_3  1.725013e+07            9.004253
4     CA_2  1.784821e+07            9.316441
5     WI_2  1.813199e+07            9.464567
6     TX_3  1.819030e+07            9.495006
7     TX_2  2.089300e+07           10.905768
8     CA_1  2.295428e+07           11.981719
9     CA_3  3.269914e+07           17.068356

In [296]:
con.sql("""WITH store_week_rev AS (
            SELECT store_id,
            wm_yr_wk,
            SUM(revenue) AS tot_weekly_rev,
            RANK() OVER( PARTITION BY store_id ORDER BY SUM(revenue) DESC) AS rank_wk
            FROM sales_daily
            GROUP BY store_id,wm_yr_wk)
            SELECT
            store_id,
            wm_yr_wk,
            tot_weekly_rev,
            rank_wk
            FROM store_week_rev
            WHERE rank_wk <4
            ORDER BY store_id""").df()

   store_id  wm_yr_wk  tot_weekly_rev  rank_wk
0      CA_1     11614       111473.48        1
1      CA_1     11527       110313.25        2
2      CA_1     11616       109908.57        3
3      CA_2     11616       112693.37        1
4      CA_2     11610       106897.44        3
5      CA_2     11614       110671.45        2
6      CA_3     11614       153107.45        1
7      CA_3     11527       152079.14        2
8      CA_3     11536       150804.11        3
9      CA_4     11614        65648.12        1
10     CA_4     11616        65299.09        2
11     CA_4     11615        64188.33        3
12     TX_1     11615        77674.95        2
13     TX_1     11607        76095.08        3
14     TX_1     11616        79924.79        1
15     TX_2     11602       102503.79        1
16     TX_2     11603        95156.03        2
17     TX_2     11607        95133.24        3
18     TX_3     11614        99416.23        3
19     TX_3     11615       100008.05        2
20     TX_3     11602       101772.07        1
21     WI_1     11614        86890.28        1
22     WI_1     11616        85502.53        3
23     WI_1     11611        86282.24        2
24     WI_2     11611       124575.99        2
25     WI_2     11610       122579.81        3
26     WI_2     11602       125229.43        1
27     WI_3     11602        85751.01        1
28     WI_3     11303        85111.48        2
29     WI_3     11223        84833.09        3

In [297]:
import duckdb

In [298]:
con = duckdb.connect('../data/practice.duckdb')

In [300]:
import duckdb

con = duckdb.connect('../data/practice.duckdb')

con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [304]:
con.sql("""SELECT * FROM item_abc LIMIT 2""").df()

,item_id,dept_id,cat_id,total_revenue,rank_revenue,cum_perc_rev,abc_rev
0,HOBBIES_1_354,HOBBIES_1,HOBBIES,498941.76,1,1.1,A
1,FOODS_3_120,FOODS_3,FOODS,465102.80,2,2.1,A

In [309]:
con.sql("""SELECT * FROM item_xyz WHERE xyz_items IS NULL LIMIT 2""").df()

Empty DataFrame
Columns: [item_id, avg_weekly_units, std_dev_units, cv_items, xyz_items]
Index: []

In [307]:
con.sql("""SELECT 
        a.item_id,
        a.abc_rev,
        x.xyz_items
        FROM item_abc a
        INNER JOIN item_xyz x
            ON a.item_id = x.item_id""").df()

            item_id abc_rev xyz_items
0     HOBBIES_1_354       A         X
1       FOODS_3_120       A         X
2     HOBBIES_1_158       A         X
3       FOODS_1_096       A         X
4       FOODS_3_586       A         X
...             ...     ...       ...
3044  HOBBIES_2_030       C         Y
3045  HOBBIES_2_025       C         X
3046  HOBBIES_2_073       C         Y
3047  HOBBIES_1_112       C         Z
3048  HOBBIES_2_047       C         X

[3049 rows x 3 columns]

In [316]:
con.sql("""
        SELECT
        a.item_id AS item_id,
        a.abc_rev AS abc_rev,
        x.xyz_items AS xyz_items
        FROM item_abc a
        LEFT JOIN item_xyz x
            ON a.item_id = x.item_id
        WHERE x.item_id IS NULL""")

┌─────────┬─────────┬───────────┐
│ item_id │ abc_rev │ xyz_items │
│ varchar │ varchar │  varchar  │
└─────────┴─────────┴───────────┘
             0 rows

In [1]:
import duckdb
con = duckdb.connect('../data/practice.duckdb')
con.sql("SET memory_limit = '4GB'")
con.sql("SET preserve_insertion_order = false")
con.sql("SET temp_directory = '../data/tmp'")

In [5]:
con.sql("""SELECT
            COUNT(*) AS join_table_rows
            FROM sales_daily s
            INNER JOIN calendar c
            ON s.wm_yr_wk = c.wm_yr_wk""").df()

   join_table_rows
0        414267630

In [7]:
con.sql("""SELECT
            COUNT(*) AS sales_daily_row_count
            FROM sales_daily""").df()

   sales_daily_row_count
0               59181090

In [8]:
con.sql("""SELECT 
            COUNT(*) 
            FROM calendar""").df()

   count_star()
0          1969

In [9]:
con.sql("SELECT * FROM sales_daily LIMIT 10").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-15,11607,0,1.12,0.00
1,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-16,11607,0,1.12,0.00
2,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-17,11607,0,1.12,0.00
3,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-18,11607,2,1.12,2.24
4,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-19,11608,0,1.12,0.00
5,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-20,11608,0,1.12,0.00
6,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-21,11608,0,1.12,0.00
7,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-22,11608,0,1.12,0.00
8,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-23,11608,0,1.12,0.00
9,HOBBIES_1_121,HOBBIES_1,HOBBIES,CA_2,CA,2016-03-24,11608,0,1.12,0.00

In [10]:
con.sql("SELECT * FROM calendar LIMIT 5").df()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,None,None,None,None,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,None,None,None,None,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,None,None,None,None,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,None,None,None,None,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,None,None,None,None,1,0,1

In [15]:
con.sql("""WITH item_rev AS (
    SELECT item_id,
           SUM(revenue) AS rev
    FROM sales_daily
    WHERE date >= '2015-01-01' AND date < '2016-01-01'
    GROUP BY item_id
)
SELECT item_id,
       ROUND(rev * 100 / SUM(rev) OVER (), 1) AS pct,
       CASE WHEN rev * 100 / SUM(rev) OVER () > 1 THEN 'Top' ELSE 'Other' END AS flag
FROM item_rev
ORDER BY pct""").df()

              item_id  pct   flag
0     HOUSEHOLD_2_367  0.0  Other
1     HOUSEHOLD_2_376  0.0  Other
2     HOUSEHOLD_2_384  0.0  Other
3     HOUSEHOLD_2_387  0.0  Other
4     HOUSEHOLD_2_390  0.0  Other
...               ...  ...    ...
3044      FOODS_3_202  0.6  Other
3045      FOODS_3_586  0.6  Other
3046    HOBBIES_1_158  0.9  Other
3047      FOODS_3_120  1.1    Top
3048    HOBBIES_1_354  1.1    Top

[3049 rows x 3 columns]

In [49]:
con.sql("""CREATE OR REPLACE TABLE store_item_coverage AS 
            SELECT
            store_id,
            COUNT(DISTINCT item_id) AS no_of_dist_item_sold,
            COUNT(DISTINCT item_id) *100.0/ (SELECT COUNT(DISTINCT item_id) FROM sales_daily) AS coverage_portfolio
            FROM sales_daily
            WHERE date BETWEEN '2016-01-01' AND '2016-12-31'
            AND units > 0
            GROUP BY store_id
            ORDER BY coverage_portfolio""")

In [50]:
con.sql("SELECT * FROM store_item_coverage").df()

  store_id  no_of_dist_item_sold  coverage_portfolio
0     CA_4                  3030           99.376845
1     TX_1                  3037           99.606428
2     WI_2                  3038           99.639226
3     CA_2                  3041           99.737619
4     CA_3                  3041           99.737619
5     WI_3                  3043           99.803214
6     TX_2                  3043           99.803214
7     TX_3                  3043           99.803214
8     WI_1                  3046           99.901607
9     CA_1                  3047           99.934405

In [52]:
con.sql("""SELECT 
           s.item_id,
           s.store_id,
           s.wm_yr_wk,
           SUM(s.units) AS tot_unit_sold,
           MAX(p.sell_price) AS price_week
           FROM sales_daily s 
           INNER JOIN prices p
            ON s.wm_yr_wk = p.wm_yr_wk
        WHERE s.item_id = 'FOODS_3_090'
        AND s.store_id = 'CA_1'
        GROUP BY s.item_id, s.store_id, s.wm_yr_wk
        ORDER BY s.wm_yr_wk DESC""").df()

         item_id store_id  wm_yr_wk  tot_unit_sold  price_week
0    FOODS_3_090     CA_1     11617      3994190.0       29.97
1    FOODS_3_090     CA_1     11616     10976400.0       29.97
2    FOODS_3_090     CA_1     11615     13446090.0       29.97
3    FOODS_3_090     CA_1     11614     14421770.0       33.72
4    FOODS_3_090     CA_1     11613     11708160.0       33.72
..           ...      ...       ...            ...         ...
273  FOODS_3_090     CA_1     11105            0.0       28.00
274  FOODS_3_090     CA_1     11104            0.0       28.00
275  FOODS_3_090     CA_1     11103            0.0       28.00
276  FOODS_3_090     CA_1     11102      3867925.0       28.00
277  FOODS_3_090     CA_1     11101      6734112.0       22.00

[278 rows x 5 columns]

In [65]:
con.sql("""WITH weekly_abs_change AS (
            SELECT
            store_id,
            wm_yr_wk,
            SUM(units) tot_units_week,
            LAG(SUM(units),1) OVER (ORDER BY wm_yr_wk) AS tot_units_pr_week,
            ABS(SUM(units) - LAG(SUM(units),1) OVER (ORDER BY wm_yr_wk)) AS wow_abs_units_change,
            FROM sales_daily
            WHERE store_id = 'CA_3'
            GROUP BY store_id, wm_yr_wk)
            SELECT
            store_id,
            wm_yr_wk,
            AVG(wow_abs_units_change) OVER () AS avg_abs_wow_change
            FROM weekly_abs_change
            """).df()

    store_id  wm_yr_wk  avg_abs_wow_change
0       CA_3     11101         2652.299639
1       CA_3     11102         2652.299639
2       CA_3     11103         2652.299639
3       CA_3     11104         2652.299639
4       CA_3     11105         2652.299639
..       ...       ...                 ...
273     CA_3     11613         2652.299639
274     CA_3     11614         2652.299639
275     CA_3     11615         2652.299639
276     CA_3     11616         2652.299639
277     CA_3     11617         2652.299639

[278 rows x 3 columns]

In [67]:
con.sql("SELECT * FROM sales_daily LIMIT 5").df()

,item_id,dept_id,cat_id,store_id,state_id,date,wm_yr_wk,units,sell_price,revenue
0,FOODS_3_498,FOODS_3,FOODS,CA_1,CA,2014-10-23,11438,0,0.2,0.0
1,FOODS_3_498,FOODS_3,FOODS,CA_1,CA,2014-10-24,11438,0,0.2,0.0
2,FOODS_3_498,FOODS_3,FOODS,CA_1,CA,2014-10-25,11439,0,0.2,0.0
3,FOODS_3_498,FOODS_3,FOODS,CA_1,CA,2014-10-26,11439,0,0.2,0.0
4,FOODS_3_498,FOODS_3,FOODS,CA_1,CA,2014-10-27,11439,13,0.2,2.6

In [73]:
con.sql("""WITH weekly_rev AS(
            SELECT 
            store_id,
            wm_yr_wk,
            SUM(revenue) AS rev_week,
            FROM sales_daily 
            WHERE store_id = 'WI_1'
            AND date BETWEEN '2015-01-01' AND '2015-12-31'
            GROUP BY wm_yr_wk, store_id)
            SELECT
            store_id,
            wm_yr_wk,
            rev_week,
            SUM(rev_week) OVER ( ORDER BY wm_yr_wk ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cum_rev
            FROM weekly_rev
            ORDER BY wm_yr_wk
            """).df()

   store_id  wm_yr_wk  rev_week     cum_rev
0      WI_1     11448  20596.24    20596.24
1      WI_1     11449  63422.72    84018.96
2      WI_1     11450  76442.29   160461.25
3      WI_1     11451  71285.54   231746.79
4      WI_1     11452  69727.67   301474.46
5      WI_1     11501  74597.54   376072.00
6      WI_1     11502  80299.22   456371.22
7      WI_1     11503  74105.83   530477.05
8      WI_1     11504  74220.16   604697.21
9      WI_1     11505  78105.65   682802.86
10     WI_1     11506  75289.82   758092.68
11     WI_1     11507  69045.00   827137.68
12     WI_1     11508  68105.47   895243.15
13     WI_1     11509  72544.64   967787.79
14     WI_1     11510  68142.06  1035929.85
15     WI_1     11511  72701.96  1108631.81
16     WI_1     11512  70242.98  1178874.79
17     WI_1     11513  72265.80  1251140.59
18     WI_1     11514  73649.08  1324789.67
19     WI_1     11515  72643.64  1397433.31
20     WI_1     11516  72716.21  1470149.52
21     WI_1     11517  67472.20  1537621.72
22     WI_1     11518  75534.49  1613156.21
23     WI_1     11519  76314.22  1689470.43
24     WI_1     11520  72895.01  1762365.44
25     WI_1     11521  66152.45  1828517.89
26     WI_1     11522  76202.38  1904720.27
27     WI_1     11523  69772.00  1974492.27
28     WI_1     11524  76227.03  2050719.30
29     WI_1     11525  70081.43  2120800.73
30     WI_1     11526  69962.60  2190763.33
31     WI_1     11527  74291.30  2265054.63
32     WI_1     11528  68059.90  2333114.53
33     WI_1     11529  69721.76  2402836.29
34     WI_1     11530  69639.94  2472476.23
35     WI_1     11531  74561.81  2547038.04
36     WI_1     11532  69962.85  2617000.89
37     WI_1     11533  72162.10  2689162.99
38     WI_1     11534  67818.34  2756981.33
39     WI_1     11535  72836.66  2829817.99
40     WI_1     11536  76387.81  2906205.80
41     WI_1     11537  74890.07  2981095.87
42     WI_1     11538  71858.77  3052954.64
43     WI_1     11539  74443.08  3127397.72
44     WI_1     11540  73381.06  3200778.78
45     WI_1     11541  73842.67  3274621.45
46     WI_1     11542  77933.25  3352554.70
47     WI_1     11543  67842.09  3420396.79
48     WI_1     11544  74730.65  3495127.44
49     WI_1     11545  79539.06  3574666.50
50     WI_1     11546  78413.95  3653080.45
51     WI_1     11547  74203.02  3727283.47
52     WI_1     11548  61785.78  3789069.25

In [80]:
con.sql("""WITH store_item_sale AS (
            SELECT 
            store_id,
            item_id,
            SUM(units) AS units_sold_2015,
            SUM(units)*100.0/ SUM(SUM(units)) OVER (PARTITION BY store_id) AS item_perc_share,
            Row_Number() OVER(PARTITION BY store_id ORDER BY SUM(units) DESC) AS item_sale_rank
            FROM sales_daily 
            WHERE date BETWEEN '2015-01-01' AND '2015-12-31'
            GROUP BY store_id, item_id)
            SELECT 
            store_id,
            item_id,
            units_sold_2015,
            item_perc_share,
            item_sale_rank
            FROM store_item_sale
            WHERE item_sale_rank < 6
            ORDER BY store_id,item_sale_rank DESC""").df()

   store_id        item_id  units_sold_2015  item_perc_share  item_sale_rank
0      CA_1    FOODS_3_282          10679.0         0.664587               5
1      CA_1    FOODS_3_252          14751.0         0.918000               4
2      CA_1    FOODS_3_120          15408.0         0.958887               3
3      CA_1    FOODS_3_586          16361.0         1.018195               2
4      CA_1    FOODS_3_090          18482.0         1.150191               1
5      CA_2    FOODS_3_555           6686.0         0.553284               5
6      CA_2    FOODS_3_288           7850.0         0.649608               4
7      CA_2    FOODS_3_090          11752.0         0.972509               3
8      CA_2    FOODS_3_586          12132.0         1.003955               2
9      CA_2    FOODS_3_252          12568.0         1.040035               1
10     CA_3  HOBBIES_1_234          13242.0         0.581618               5
11     CA_3    FOODS_3_252          16695.0         0.733281               4
12     CA_3    FOODS_3_586          26792.0         1.176764               3
13     CA_3    FOODS_3_120          31598.0         1.387854               2
14     CA_3    FOODS_3_090          33279.0         1.461687               1
15     CA_4    FOODS_3_282           3925.0         0.448520               5
16     CA_4    FOODS_3_586           4607.0         0.526454               4
17     CA_4    FOODS_3_714           4925.0         0.562792               3
18     CA_4    FOODS_3_587           5291.0         0.604616               2
19     CA_4    FOODS_3_090           9048.0         1.033938               1
20     TX_1    FOODS_3_555           8556.0         0.743192               5
21     TX_1    FOODS_3_587          10137.0         0.880520               4
22     TX_1    FOODS_3_252          11181.0         0.971204               3
23     TX_1    FOODS_3_090          14415.0         1.252116               2
24     TX_1    FOODS_3_586          18387.0         1.597132               1
25     TX_2    FOODS_3_587          11266.0         0.825470               5
26     TX_2    FOODS_3_555          16412.0         1.202521               4
27     TX_2    FOODS_3_090          17523.0         1.283925               3
28     TX_2    FOODS_3_252          21479.0         1.573785               2
29     TX_2    FOODS_3_586          33811.0         2.477361               1
30     TX_3    FOODS_3_555          12345.0         0.919298               5
31     TX_3    FOODS_3_377          14698.0         1.094519               4
32     TX_3    FOODS_3_252          17502.0         1.303325               3
33     TX_3    FOODS_3_090          19415.0         1.445781               2
34     TX_3    FOODS_3_586          27030.0         2.012849               1
35     WI_1    FOODS_3_714           5272.0         0.413515               5
36     WI_1    FOODS_3_586           5945.0         0.466302               4
37     WI_1    FOODS_3_090           6481.0         0.508344               3
38     WI_1    FOODS_3_694           7013.0         0.550072               2
39     WI_1    FOODS_3_226          15020.0         1.178109               1
40     WI_2    FOODS_3_007           9811.0         0.650757               5
41     WI_2    FOODS_3_694          10588.0         0.702295               4
42     WI_2    FOODS_3_587          10793.0         0.715893               3
43     WI_2    FOODS_1_096          12562.0         0.833229               2
44     WI_2    FOODS_3_226          12956.0         0.859363               1
45     WI_3    FOODS_3_586          12086.0         1.013758               5
46     WI_3    FOODS_3_120          12169.0         1.020720               4
47     WI_3    FOODS_3_694          15810.0         1.326122               3
48     WI_3    FOODS_3_226          17515.0         1.469135               2
49     WI_3    FOODS_3_090          19883.0         1.667760               1